In [1]:
import torch

In [2]:
torch.__version__ #to check version of pytorch

'2.3.1'

<h1>Introduction to tensors</h1>

<h2>Creating tensors</h2>

<h3>01.Scaler</h3>

In [3]:
s = torch.tensor(8) #to create a scalar value
s

tensor(8)

In [9]:
s.item() #to extract item form scaler

8

In [13]:
s.ndim #to check dimensons

0

In [17]:
s.shape #to check the shape of dimention

torch.Size([])

<h3>02.Vector</h3>

In [18]:
v = torch.tensor([3,4,1])
v

tensor([3, 4, 1])

In [19]:
v.ndim #count starting or last square brackets to know the dimension

1

In [20]:
v.shape

torch.Size([3])

<h3>03.Matrix</h3>

In [21]:
m = torch.tensor([[1,2,3],[4,5,6]])
m

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
m.ndim

2

In [23]:
m.shape

torch.Size([2, 3])

<h3>3D tensors</h3>

In [30]:
t = torch.tensor([[[1,2,3,4],[4,5,6,4],[7,8,9,4]]])
t

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 4]]])

In [31]:
t.ndim

3

In [32]:
t.shape

torch.Size([1, 3, 4])

<h3>Random tensors</h3>

In [36]:
rt = torch.rand(3,4) #rt = torch.rand(rows, columns)
rt

tensor([[0.6051, 0.3738, 0.6500, 0.7905],
        [0.1192, 0.8127, 0.7939, 0.9664],
        [0.5658, 0.0173, 0.7633, 0.2540]])

In [37]:
brt = torch.rand(1,3,4)
brt

tensor([[[0.8186, 0.4968, 0.9270, 0.1388],
         [0.8353, 0.0541, 0.3857, 0.3598],
         [0.6299, 0.0484, 0.5401, 0.1418]]])

In [38]:
brt2 = torch.rand(2,3,4)
brt2

tensor([[[0.5416, 0.6978, 0.5812, 0.3753],
         [0.1765, 0.1646, 0.8545, 0.6751],
         [0.4126, 0.4928, 0.9522, 0.1187]],

        [[0.2180, 0.2381, 0.3152, 0.5759],
         [0.4615, 0.9177, 0.9120, 0.3553],
         [0.9490, 0.8095, 0.2599, 0.5248]]])