In [1]:
import torch

In [2]:
torch.__version__ #to check version of pytorch

'2.3.1'

<h1>Introduction to tensors</h1>

<h2>Creating tensors</h2>

<h3>01.Scaler</h3>

In [3]:
s = torch.tensor(8) #to create a scalar value
s

tensor(8)

In [4]:
s.item() #to extract item form scaler

8

In [5]:
s.ndim #to check dimensons

0

In [6]:
s.shape #to check the shape of dimention

torch.Size([])

<h3>02.Vector</h3>

In [7]:
v = torch.tensor([3,4,1])
v

tensor([3, 4, 1])

In [8]:
v.ndim #count starting or last square brackets to know the dimension

1

In [9]:
v.shape

torch.Size([3])

<h3>03.Matrix</h3>

In [10]:
m = torch.tensor([[1,2,3],[4,5,6]])
m

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
m.ndim

2

In [12]:
m.shape

torch.Size([2, 3])

<h3>3D tensors</h3>

In [13]:
t = torch.tensor([[[1,2,3,4],[4,5,6,4],[7,8,9,4]]])
t

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 4]]])

In [14]:
t.ndim

3

In [15]:
t.shape

torch.Size([1, 3, 4])

<h3>Random tensors</h3>

In [16]:
rt = torch.rand(3,4) #rt = torch.rand(rows, columns)
rt

tensor([[0.9979, 0.2914, 0.5755, 0.6319],
        [0.5650, 0.7345, 0.6183, 0.8408],
        [0.4807, 0.9549, 0.5928, 0.4872]])

In [17]:
brt = torch.rand(1,3,4)
brt

tensor([[[0.9160, 0.0388, 0.6801, 0.6711],
         [0.5324, 0.1821, 0.3738, 0.4142],
         [0.8622, 0.3839, 0.7398, 0.0892]]])

In [18]:
brt2 = torch.rand(2,3,4)
brt2

tensor([[[0.8800, 0.5882, 0.3411, 0.2444],
         [0.9078, 0.3386, 0.5710, 0.5252],
         [0.9716, 0.7031, 0.8536, 0.2265]],

        [[0.6923, 0.2431, 0.6978, 0.1010],
         [0.1075, 0.7279, 0.7855, 0.6277],
         [0.2516, 0.5058, 0.9258, 0.8801]]])

<h1>Zeros</h1>

In [20]:
z = torch.zeros(3,4)
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

<h1>Ones</h1>

In [22]:
o = torch.ones(3,4)
o

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

<h1>Creating arange</h1>

In [24]:
a1 = torch.arange(1,10) #a = torch.arange(start, end)
a1

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a2 = torch.arange(1,10,2) #a = torch.arange(start, end, step)
a2

tensor([1, 3, 5, 7, 9])

<h1>Tensor_like</h1>

In [31]:
t = torch.tensor([[1,3,5,7],[5,3,5,1]])
t

tensor([[1, 3, 5, 7],
        [5, 3, 5, 1]])

In [33]:
zl = torch.zeros_like(t) #to create zeros tensor with given tensor dimension
zl

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [35]:
ol = torch.ones_like(t) #to create ones tensor with given tensor dimension
ol

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

<h2>torch.eye (unit / identity matrix)</h2>

In [37]:
e = torch.eye(5) #to make 2D digonal one tensor
e

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

<h2>torch.full</h2>

In [40]:
f = torch.full((3,4),1) #torch.full((start, end),filling number)to create a tensor filled with a specific value
f

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

<h2>torch.linspace</h2>

In [43]:
l = torch.linspace(1,10,5) #to create a tensor with linearspace => torch.linspace(start, end, total_number)
l

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])