<h1>Pytorch Basic</h1>

In [191]:
import torch

In [192]:
torch.__version__ #to check version of pytorch

'2.3.1'

<h2>Creating tensors</h2>

<h3>01.Scaler</h3>

In [193]:
s = torch.tensor(8) #to create tensor

In [194]:
s #to show tensor

tensor(8)

In [195]:
s.dtype #to check datatype

torch.int64

In [196]:
s.ndim #to check dimensons

0

In [197]:
s.shape #to check shape

torch.Size([])

In [198]:
s.item() #to extract item form scaler

8

<h3>02.Vector</h3>

In [199]:
v = torch.tensor([3,4,1])
v

tensor([3, 4, 1])

In [200]:
v.ndim #count starting or last square brackets to know the dimension

1

In [201]:
v.shape

torch.Size([3])

<h3>03.Matrix</h3>

In [202]:
m = torch.tensor([[1,2,3],[4,5,6]])
m

tensor([[1, 2, 3],
        [4, 5, 6]])

In [203]:
m.ndim

2

In [204]:
m.shape

torch.Size([2, 3])

<h3>3D tensors</h3>

In [205]:
t = torch.tensor([[[1,2,3,4],[4,5,6,4],[7,8,9,4]]])
t

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 4]]])

In [206]:
t.ndim

3

In [207]:
t.shape

torch.Size([1, 3, 4])

<h3>Random tensors</h3>

In [162]:
rt = torch.rand(3,4) #rt = torch.rand(rows, columns)
rt

tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])

In [163]:
brt = torch.rand(1,3,4)
brt

tensor([[[0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895]]])

In [164]:
brt2 = torch.rand(2,3,4)
brt2

tensor([[[0.7539, 0.1952, 0.0050, 0.3068],
         [0.1165, 0.9103, 0.6440, 0.7071],
         [0.6581, 0.4913, 0.8913, 0.1447]],

        [[0.5315, 0.1587, 0.6542, 0.3278],
         [0.6532, 0.3958, 0.9147, 0.2036],
         [0.2018, 0.2018, 0.9497, 0.6666]]])

<h1>Zeros</h1>

In [165]:
z = torch.zeros(3,4)
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

<h1>Ones</h1>

In [166]:
o = torch.ones(3,4)
o

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

<h1>Creating arange</h1>

In [167]:
a1 = torch.arange(1,10) #a = torch.arange(start, end)
a1

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
a2 = torch.arange(1,10,2) #a = torch.arange(start, end, step)
a2

tensor([1, 3, 5, 7, 9])

<h1>Tensor_like</h1>

In [169]:
t = torch.tensor([[1,3,5,7],[5,3,5,1]])
t

tensor([[1, 3, 5, 7],
        [5, 3, 5, 1]])

In [170]:
zl = torch.zeros_like(t) #to create zeros tensor with given tensor dimension
zl

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [171]:
ol = torch.ones_like(t) #to create ones tensor with given tensor dimension
ol

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

<h2>torch.eye (unit / identity matrix)</h2>

In [172]:
e = torch.eye(5) #to make 2D digonal one tensor
e

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

<h2>torch.full</h2>

In [173]:
f = torch.full((3,4),1) #torch.full((start, end),filling number)to create a tensor filled with a specific value
f

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

<h2>torch.linspace</h2>

In [174]:
l = torch.linspace(1,10,5) #to create a tensor with linearspace => torch.linspace(start, end, total_number)
l

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

<h2>Tensor datatype</h2>
<h3>Scaler</h3>

In [175]:
s = torch.tensor(1)
print(s)
print(s.dtype)

tensor(1)
torch.int64


In [176]:
s = torch.tensor(1.) #it will return a floating point number
print(s)
print(s.dtype)

tensor(1.)
torch.float32


<h3>Vector</h3>

In [177]:
v = torch.tensor([1,2,3,4])
print(v)
print(v.dtype)

tensor([1, 2, 3, 4])
torch.int64


In [178]:
v = torch.tensor([1,2.,3,4]) #it will converts all numbers into float because one number is float
print(v)
print(v.dtype)

tensor([1., 2., 3., 4.])
torch.float32


<h3>Matrix</h3>

In [179]:
m = torch.tensor([[1,2,3],[4,5,6]])
print(m)
print(m.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64


In [180]:
m = torch.tensor([[1,2.,4], [4,5,6]]) #it will converts all numbers into float because one number is float
print(m)
print(m.dtype)

tensor([[1., 2., 4.],
        [4., 5., 6.]])
torch.float32


In [181]:
t = torch.rand(3,4) #float32
print(t)
print(t.dtype)

tensor([[0.9811, 0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790, 0.9155],
        [0.2418, 0.1591, 0.7653, 0.2979]])
torch.float32


In [182]:
t = torch.arange(3,14)
print(t)
print(t.dtype)

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
torch.int64


In [183]:
t = torch.arange(3.,14.,dtype=float) #define datatype
print(t)
print(t.dtype)

tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       dtype=torch.float64)
torch.float64


<h2>Changing tensor datatype</h2>

In [184]:
t = torch.arange(1,10) #Change datatype into floating point numbers
print(t)
print(t.dtype)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64


In [185]:
f16 = t.type(torch.float16) #to change datatype into float16
f16

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

In [186]:
i8 = t.type(torch.int8) #to change datatype into int8
i8

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8)

In [188]:
t = torch.tensor([[1,2,3,4],[4,5,6,7]], dtype=torch.int32)
print(t)
print(t.dtype)

tensor([[1, 2, 3, 4],
        [4, 5, 6, 7]], dtype=torch.int32)
torch.int32


In [189]:
t = torch.tensor([[1,2,3,4],[4,5,6,7]], dtype=torch.float16)
print(t)
print(t.dtype)

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]], dtype=torch.float16)
torch.float16


<h2>Getting information from tensor</h2>

In [35]:
t = torch.rand(3,4)
t

tensor([[0.2433, 0.6232, 0.2802, 0.2870],
        [0.7299, 0.7440, 0.8448, 0.9046],
        [0.9770, 0.6109, 0.5798, 0.3391]])

In [36]:
t.shape

torch.Size([3, 4])

In [37]:
t.dtype

torch.float32

In [38]:
t.device

device(type='cpu')

<h2>Manipulating tensors (tensor oprations)</h2>

<h3>
    <pre>
    1.Addition
    2.Substraction
    3.Element_wise multiplication
    4.Matrix multiplication
    5.Division
    </pre>
</h3>

<h3>1.Addition</h3>

In [39]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
print(t1)
print(t2)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [40]:
ma = t1+t2
ma

tensor([5, 7, 9])

In [41]:
ma = torch.add(t1,t2)
ma

tensor([5, 7, 9])

In [42]:
sa = t1+10
sa

tensor([11, 12, 13])

In [43]:
sa = torch.add(t1,15)
sa

tensor([16, 17, 18])

<h3>2.Substraction</h3>

In [44]:
t1 = torch.tensor([1,2,3,4])
t2 = torch.tensor([4,5,6,7])
print(t1)
print(t2)

tensor([1, 2, 3, 4])
tensor([4, 5, 6, 7])


In [45]:
ms = t2-t1
ms

tensor([3, 3, 3, 3])

In [46]:
ms = torch.sub(t2,t1)
ms

tensor([3, 3, 3, 3])

In [47]:
ss = t2 - 2
ss

tensor([2, 3, 4, 5])

In [48]:
ss = torch.sub(t2,2)
ss

tensor([2, 3, 4, 5])

<h3>3.Element-wise multiplication</h3>

In [49]:
t1 = torch.tensor([1,2,3,4])
t2 = torch.tensor([4,5,6,7])
print(t1)
print(t2)

tensor([1, 2, 3, 4])
tensor([4, 5, 6, 7])


In [50]:
me = t1 * t2
me

tensor([ 4, 10, 18, 28])

In [51]:
me = torch.mul(t1,t2)
me

tensor([ 4, 10, 18, 28])

In [52]:
me = torch.multiply(t1,t2)
me

tensor([ 4, 10, 18, 28])

In [53]:
es = 3*t1
es

tensor([ 3,  6,  9, 12])

In [54]:
es = torch.mul(3,t1)
es

tensor([ 3,  6,  9, 12])

In [55]:
es = torch.multiply(3,t1)
es

tensor([ 3,  6,  9, 12])

<h3>4.Division</h3>

In [56]:
t1 = torch.tensor([1,2,3,4])
t2 = torch.tensor([4,5,6,7])
print(t1)
print(t2)

tensor([1, 2, 3, 4])
tensor([4, 5, 6, 7])


In [57]:
md = t2 / t1
md

tensor([4.0000, 2.5000, 2.0000, 1.7500])

In [58]:
md = torch.div(t2, t1)
md

tensor([4.0000, 2.5000, 2.0000, 1.7500])

In [59]:
sd = 20 / t2
sd

tensor([5.0000, 4.0000, 3.3333, 2.8571])

In [60]:
sd = torch.div(20, t2)
sd

tensor([5.0000, 4.0000, 3.3333, 2.8571])

<h3>5.Matrix multiplication</h3>

In [61]:
m1 = torch.tensor([[1,2,3,4],[5,6,7,8]])
m2 = torch.tensor([[8,7,6,5],[4,3,2,1]])
print(m1)
print(m2)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[8, 7, 6, 5],
        [4, 3, 2, 1]])


In [62]:
m1.shape, m2.shape

(torch.Size([2, 4]), torch.Size([2, 4]))

In [63]:
trans = m2.T
trans

tensor([[8, 4],
        [7, 3],
        [6, 2],
        [5, 1]])

In [64]:
m1.shape, trans.shape

(torch.Size([2, 4]), torch.Size([4, 2]))

In [65]:
result = m1 @ trans #to matrix multiplication
result

tensor([[ 60,  20],
        [164,  60]])

In [66]:
result = torch.mm(m1, trans)
result

tensor([[ 60,  20],
        [164,  60]])

In [67]:
result = torch.matmul(m1,trans)
result

tensor([[ 60,  20],
        [164,  60]])

<h2>Concatenate two value with compatible shape</h2>

In [219]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

In [220]:
z = torch.concat((x,y))
z

tensor([1, 2, 3, 4, 5, 6])

In [218]:
z = x+y
z

tensor([5, 7, 9])

<h2>Finding the Mean, Min,, Max, and Sum</h2>

In [68]:
x = torch.tensor([[1.,2,3,4],[4,5,6,7]]) #it's alwas works with floating point numbers
x

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])

In [69]:
x.mean() #to find mean value

tensor(4.)

In [70]:
x.min() #to find minimum value

tensor(1.)

In [71]:
x.max() #to find maximum value

tensor(7.)

In [72]:
x.sum() #to sum all of the values

tensor(32.)

In [73]:
torch.mean(x) #to find mean value

tensor(4.)

In [74]:
torch.min(x) #to find minimum value

tensor(1.)

In [75]:
torch.max(x) #to find maximum value

tensor(7.)

In [76]:
torch.sum(x) #to sum all of the values

tensor(32.)

<h2>Positional Min and Max</h2>

In [77]:
x.argmin() #to find index of minimum number

tensor(0)

In [78]:
x.argmax() #to find index of maximum number

tensor(7)

<h3>Reshaping</h3>

In [79]:
x = torch.arange(1,9)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
x_reshaped = x.reshape(2,4)
x_reshaped

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [81]:
x_reshaped1 = x.reshape(2,2,2)
x_reshaped1

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [82]:
y = torch.arange(1,9)
y

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
y_view = y.view(2,4)
y_view

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

<h3>Stacking</h3>

In [84]:
t = torch.arange(1,9)
t

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
t_stack = torch.stack([t,t,t]) #add row-wise (default "dim=0")
t_stack

tensor([[1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8]])

In [86]:
t_stack = torch.stack([t,t,t], dim=1) #add columnwise
t_stack

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8]])

<h3>Unsqueeze</h3>

In [87]:
x = torch.tensor([1,2,3,4,5,6])
x

tensor([1, 2, 3, 4, 5, 6])

In [88]:
print(x.shape)
print(x.ndim)

torch.Size([6])
1


In [89]:
ur = torch.unsqueeze(x,dim=0) #to add 1D (row-wise)
ur

tensor([[1, 2, 3, 4, 5, 6]])

In [90]:
print(ur.shape)
print(ur.ndim)

torch.Size([1, 6])
2


In [91]:
uc = torch.unsqueeze(x,dim=1) #to add 1D (column-wise)
uc

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [92]:
print(uc.shape)
print(uc.ndim)

torch.Size([6, 1])
2


<h3>Squeeze</h3>

In [93]:
x = torch.tensor([[1,2,3,4,5,6,7]])
x

tensor([[1, 2, 3, 4, 5, 6, 7]])

In [94]:
print(x.shape)
print(x.ndim)

torch.Size([1, 7])
2


In [95]:
sr = x.squeeze() #to remove 1D
sr

tensor([1, 2, 3, 4, 5, 6, 7])

In [96]:
print(sr.shape)
print(sr.ndim)

torch.Size([7])
1


<h3>Permute</h3>

In [97]:
x = torch.rand(2,3,4)
x

tensor([[[0.4363, 0.9865, 0.4110, 0.6052],
         [0.5454, 0.3513, 0.6220, 0.0868],
         [0.4277, 0.2493, 0.3777, 0.6098]],

        [[0.7943, 0.7665, 0.3310, 0.9523],
         [0.2586, 0.7764, 0.9960, 0.0713],
         [0.8894, 0.2142, 0.1665, 0.0374]]])

In [98]:
print(x.shape)
print(x.ndim)

torch.Size([2, 3, 4])
3


In [99]:
x_permute = torch.permute(x,[2,0,1]) #to rearrange the dimension of tensor (it takes the index of item as argument
x_permute

tensor([[[0.4363, 0.5454, 0.4277],
         [0.7943, 0.2586, 0.8894]],

        [[0.9865, 0.3513, 0.2493],
         [0.7665, 0.7764, 0.2142]],

        [[0.4110, 0.6220, 0.3777],
         [0.3310, 0.9960, 0.1665]],

        [[0.6052, 0.0868, 0.6098],
         [0.9523, 0.0713, 0.0374]]])

In [100]:
print(x_permute.shape)
print(x_permute.ndim)

torch.Size([4, 2, 3])
3


<h3>Indexing (Selecting data from tensors)</h3>

In [101]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [102]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [103]:
x[0,0]

tensor([1, 2, 3])

In [104]:
x[0,0,0]

tensor(1)

In [105]:
x[0,1,2]

tensor(6)

<h3>Pytorch tensor and Numpy array</h3>

In [106]:
import numpy as np

In [107]:
n = np.arange(1,9)
n

array([1, 2, 3, 4, 5, 6, 7, 8])

In [108]:
t = torch.from_numpy(n) #to convert numpy array into pytorch tensor
t

tensor([1, 2, 3, 4, 5, 6, 7, 8], dtype=torch.int32)

In [109]:
n = t.numpy() #to convet pytorch tensor into numpy array
n

array([1, 2, 3, 4, 5, 6, 7, 8])

<h2>Reproducibility</h2>

<h3>This will not return you a fix value</h3>

In [110]:
r1 = torch.rand(3,4)
r2 = torch.rand(3,4)
print(r1)
print(r2)

tensor([[0.6285, 0.3057, 0.9454, 0.3728],
        [0.4972, 0.7692, 0.3525, 0.7964],
        [0.0154, 0.4323, 0.9799, 0.8937]])
tensor([[0.5371, 0.0249, 0.4815, 0.7219],
        [0.6167, 0.6687, 0.6337, 0.4224],
        [0.9254, 0.2248, 0.7802, 0.6737]])


<h3>This will return you a fix value</h3>

In [111]:
torch.manual_seed(42)
r1 = torch.rand(3,4)
print(r1)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [112]:
torch.manual_seed(42)
r2 = torch.rand(3,4)
r2

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

<h2>Running Tensor on GPU</h2>

In [113]:
torch.cuda.is_available() #if false, there is not any GPU

True

In [114]:
torch.cuda.device_count() #to count available devices

1

In [115]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [116]:
t = torch.arange(1,11)
t

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
t.device #to check tensor running on cpu or gpu

device(type='cpu')

In [118]:
tg = t.to(device) #to send on gpu
tg.device

device(type='cuda', index=0)