In [2]:
import torch

In [3]:
torch.__version__ #to check version of pytorch

'2.3.1'

<h1>Introduction to tensors</h1>

<h2>Creating tensors</h2>

<h3>01.Scaler</h3>

In [4]:
s = torch.tensor(8) #to create a scalar value
s

tensor(8)

In [5]:
s.item() #to extract item form scaler

8

In [6]:
s.ndim #to check dimensons

0

In [7]:
s.shape #to check the shape of dimention

torch.Size([])

<h3>02.Vector</h3>

In [8]:
v = torch.tensor([3,4,1])
v

tensor([3, 4, 1])

In [9]:
v.ndim #count starting or last square brackets to know the dimension

1

In [10]:
v.shape

torch.Size([3])

<h3>03.Matrix</h3>

In [11]:
m = torch.tensor([[1,2,3],[4,5,6]])
m

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
m.ndim

2

In [13]:
m.shape

torch.Size([2, 3])

<h3>3D tensors</h3>

In [14]:
t = torch.tensor([[[1,2,3,4],[4,5,6,4],[7,8,9,4]]])
t

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 4]]])

In [15]:
t.ndim

3

In [16]:
t.shape

torch.Size([1, 3, 4])

<h3>Random tensors</h3>

In [17]:
rt = torch.rand(3,4) #rt = torch.rand(rows, columns)
rt

tensor([[0.5860, 0.0482, 0.9707, 0.8545],
        [0.4275, 0.1446, 0.6643, 0.8384],
        [0.8370, 0.6363, 0.7001, 0.8267]])

In [18]:
brt = torch.rand(1,3,4)
brt

tensor([[[0.0939, 0.4460, 0.1960, 0.6617],
         [0.7826, 0.5612, 0.9983, 0.1527],
         [0.0196, 0.3225, 0.5994, 0.0587]]])

In [19]:
brt2 = torch.rand(2,3,4)
brt2

tensor([[[0.3132, 0.0119, 0.5649, 0.8062],
         [0.7524, 0.6728, 0.9002, 0.8310],
         [0.9275, 0.4126, 0.4405, 0.1383]],

        [[0.4873, 0.1211, 0.0788, 0.7040],
         [0.6398, 0.9000, 0.4906, 0.1563],
         [0.2784, 0.2515, 0.7737, 0.5289]]])

<h1>Zeros</h1>

In [20]:
z = torch.zeros(3,4)
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

<h1>Ones</h1>

In [21]:
o = torch.ones(3,4)
o

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

<h1>Creating arange</h1>

In [22]:
a1 = torch.arange(1,10) #a = torch.arange(start, end)
a1

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a2 = torch.arange(1,10,2) #a = torch.arange(start, end, step)
a2

tensor([1, 3, 5, 7, 9])

<h1>Tensor_like</h1>

In [24]:
t = torch.tensor([[1,3,5,7],[5,3,5,1]])
t

tensor([[1, 3, 5, 7],
        [5, 3, 5, 1]])

In [25]:
zl = torch.zeros_like(t) #to create zeros tensor with given tensor dimension
zl

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [26]:
ol = torch.ones_like(t) #to create ones tensor with given tensor dimension
ol

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

<h2>torch.eye (unit / identity matrix)</h2>

In [27]:
e = torch.eye(5) #to make 2D digonal one tensor
e

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

<h2>torch.full</h2>

In [28]:
f = torch.full((3,4),1) #torch.full((start, end),filling number)to create a tensor filled with a specific value
f

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

<h2>torch.linspace</h2>

In [29]:
l = torch.linspace(1,10,5) #to create a tensor with linearspace => torch.linspace(start, end, total_number)
l

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

<h2>Tensor datatype</h2>

In [30]:
t = torch.rand(3,4) #float32
print(t)
print(t.dtype)

tensor([[0.7856, 0.7217, 0.9691, 0.3593],
        [0.5379, 0.6268, 0.6613, 0.8234],
        [0.6498, 0.1105, 0.9214, 0.5293]])
torch.float32


In [31]:
t = torch.arange(3,14)
print(t)
print(t.dtype)

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
torch.int64


In [32]:
t = torch.arange(3.,14.,dtype=float) #define datatype
print(t)
print(t.dtype)

tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       dtype=torch.float64)
torch.float64


<h2>Changing tensor datatype</h2>

In [33]:
t = torch.arange(1,10) #Change datatype into floating point numbers
print(t)
print(t.dtype)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64


In [34]:
f16 = t.type(torch.float16) #to change datatype into float16
f16

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

In [35]:
i8 = t.type(torch.int8) #to change datatype into int8
i8

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8)

<h2>Getting information from tensor</h2>

In [36]:
t = torch.rand(3,4)
t

tensor([[0.5966, 0.8489, 0.5656, 0.1111],
        [0.8687, 0.7447, 0.4681, 0.1419],
        [0.2706, 0.5252, 0.2086, 0.0520]])

In [37]:
t.shape

torch.Size([3, 4])

In [38]:
t.dtype

torch.float32

In [39]:
t.device

device(type='cpu')

<h2>Manipulating tensors (tensor oprations)</h2>

<h3>
    <pre>
    1.Addition
    2.Substraction
    3.Element_wise multiplication
    4.Matrix multiplication
    5.Division
    </pre>
</h3>

<h3>1.Addition</h3>

In [40]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
print(t1)
print(t2)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [41]:
ma = t1+t2
ma

tensor([5, 7, 9])

In [42]:
ma = torch.add(t1,t2)
ma

tensor([5, 7, 9])

In [43]:
sa = t1+10
sa

tensor([11, 12, 13])

In [44]:
sa = torch.add(t1,15)
sa

tensor([16, 17, 18])

<h3>2.Substraction</h3>

In [45]:
t1 = torch.tensor([1,2,3,4])
t2 = torch.tensor([4,5,6,7])
print(t1)
print(t2)

tensor([1, 2, 3, 4])
tensor([4, 5, 6, 7])


In [46]:
ms = t2-t1
ms

tensor([3, 3, 3, 3])

In [47]:
ms = torch.sub(t2,t1)
ms

tensor([3, 3, 3, 3])

In [48]:
ss = t2 - 2
ss

tensor([2, 3, 4, 5])

In [49]:
ss = torch.sub(t2,2)
ss

tensor([2, 3, 4, 5])

<h3>3.Element-wise multiplication</h3>

In [50]:
t1 = torch.tensor([1,2,3,4])
t2 = torch.tensor([4,5,6,7])
print(t1)
print(t2)

tensor([1, 2, 3, 4])
tensor([4, 5, 6, 7])


In [51]:
me = t1 * t2
me

tensor([ 4, 10, 18, 28])

In [52]:
me = torch.mul(t1,t2)
me

tensor([ 4, 10, 18, 28])

In [53]:
me = torch.multiply(t1,t2)
me

tensor([ 4, 10, 18, 28])

In [54]:
es = 3*t1
es

tensor([ 3,  6,  9, 12])

In [55]:
es = torch.mul(3,t1)
es

tensor([ 3,  6,  9, 12])

In [56]:
es = torch.multiply(3,t1)
es

tensor([ 3,  6,  9, 12])

<h3>4.Division</h3>

In [57]:
t1 = torch.tensor([1,2,3,4])
t2 = torch.tensor([4,5,6,7])
print(t1)
print(t2)

tensor([1, 2, 3, 4])
tensor([4, 5, 6, 7])


In [58]:
md = t2 / t1
md

tensor([4.0000, 2.5000, 2.0000, 1.7500])

In [62]:
md = torch.div(t2, t1)
md

tensor([4.0000, 2.5000, 2.0000, 1.7500])

In [63]:
sd = 20 / t2
sd

tensor([5.0000, 4.0000, 3.3333, 2.8571])

In [64]:
sd = torch.div(20, t2)
sd

tensor([5.0000, 4.0000, 3.3333, 2.8571])

<h3>5.Matrix multiplication</h3>

In [65]:
m1 = torch.tensor([[1,2,3,4],[5,6,7,8]])
m2 = torch.tensor([[8,7,6,5],[4,3,2,1]])
print(m1)
print(m2)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[8, 7, 6, 5],
        [4, 3, 2, 1]])


In [66]:
m1.shape, m2.shape

(torch.Size([2, 4]), torch.Size([2, 4]))

In [68]:
trans = m2.T
trans

tensor([[8, 4],
        [7, 3],
        [6, 2],
        [5, 1]])

In [69]:
m1.shape, trans.shape

(torch.Size([2, 4]), torch.Size([4, 2]))

In [71]:
result = m1 @ trans #to matrix multiplication
result

tensor([[ 60,  20],
        [164,  60]])

In [72]:
result = torch.mm(m1, trans)
result

tensor([[ 60,  20],
        [164,  60]])

In [73]:
result = torch.matmul(m1,trans)
result

tensor([[ 60,  20],
        [164,  60]])