43:14 / 1:43:32

In [2]:
import pandas as pd #pip install pandas -q

C:\Users\Abdul\AppData\Local\Temp\ipykernel_12672\3688822733.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd #pip install pandas -q


In [4]:
df = pd.read_csv("apple_yields.csv")
df

Region  Temp. (F)  Rainfall (mm)  Humidity (%)  Apples (ton)  Oranges (ton)
0   Kanto         73             67            43            56             70
1   Johto         91             88            64            81            101
2   Hoenn         87            134            58           119            133
3  Sinnoh        102             43            37            22             37
4   Unova         69             96            70           103            119

yield_apple = w11 * temp * w12 * rainfall * w13 * humidity + b1 <br>
yield_orange = w21 * temp * w22 * rainfall * w23 * humidity + b2

In [6]:
import torch
import numpy as np

Training data

In [11]:
"""inputs = (temp, rainfall, humidity)"""
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134,58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')
print(inputs)

[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]]


In [12]:
"""targets = (apples, oranges)"""
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [32]:
"""Converts inputs and targets to tensor"""
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [33]:
"""weights and biases"""
w = torch.randn(2,3, requires_grad=True) #Matrix
b = torch.randn(2, requires_grad=True) #Vector
print(w)
print(b)

tensor([[-0.5394, -0.1394, -1.3916],
        [-0.0465,  0.2102, -1.5088]], requires_grad=True)
tensor([-0.8825,  0.3011], requires_grad=True)


In [34]:
inputs @ w.t() + b

tensor([[-109.4336,  -53.8813],
        [-151.2928,  -81.9866],
        [-147.1971,  -63.0777],
        [-113.3809,  -51.2216],
        [-148.8911,  -88.3352]], grad_fn=<AddBackward0>)

In [31]:
x = torch.tensor([[1,2,3], [4,5,6]])
y = torch.tensor([[6,5,4], [3,2,1]])
print(x)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[6, 5, 4],
        [3, 2, 1]])


In [25]:
x * y

tensor([[ 6, 10, 12],
        [12, 10,  6]])

In [28]:
d = y.t() #to transpose
d

tensor([[6, 3],
        [5, 2],
        [4, 1]])

In [27]:
x @ d

tensor([[28, 10],
        [73, 28]])

In [37]:
"""Make calculation using function"""
def model(x):
    return x @ w.t() + b

In [38]:
preds = model(inputs)
print(preds)

tensor([[-109.4336,  -53.8813],
        [-151.2928,  -81.9866],
        [-147.1971,  -63.0777],
        [-113.3809,  -51.2216],
        [-148.8911,  -88.3352]], grad_fn=<AddBackward0>)


In [39]:
"""Compare with targets"""
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [41]:
"""check differences"""
diff = preds - targets
diff

tensor([[-165.4336, -123.8813],
        [-232.2928, -182.9866],
        [-266.1971, -196.0777],
        [-135.3809,  -88.2216],
        [-251.8911, -207.3352]], grad_fn=<SubBackward0>)

In [43]:
"""to change all nigative numbers into positive"""
diff * diff

tensor([[27368.2832, 15346.5879],
        [53959.9375, 33484.0977],
        [70860.8672, 38446.4531],
        [18327.9766,  7783.0552],
        [63449.1484, 42987.8867]], grad_fn=<MulBackward0>)