<h2>Get GPU Details</h2>

In [4]:
!nvidia-smi

Fri May 30 12:39:24 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.19                 Driver Version: 561.19         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce MX130         WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A    0C    P0             N/A /  200W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
import torch

In [5]:
torch.cuda.is_available() #to check GPU (it will return true if available else false)

True

In [6]:
print("GPU Name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU detected")

GPU Name: NVIDIA GeForce MX130


In [7]:
torch.cuda.device_count() #to count available GPUs

1

<h2>Work with GPU</h2>

<h3>Embedding device with code</h3>

In [39]:
t = torch.tensor([[1,2,3],[4,5,6]], device="cuda")
t

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [40]:
t.device #to check tensor running on CPU or GPU

device(type='cuda', index=0)

In [45]:
t = torch.tensor([[1,2,3],[4,5,6]], device="cpu") #cpu is default

In [46]:
t.device

device(type='cpu')

In [47]:
t = torch.tensor([[1,2,3],[4,5,6]])
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [44]:
t.device

device(type='cpu')

<h2>Dynamic way to run code on GPU if available else CPU</h2>

In [49]:
if torch.cuda.is_available():
    device1 = torch.device("cuda")
else:
    device1 = torch.divice("cpu")
    
device

device(type='cuda')

In [50]:
device2 = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device2

device(type='cuda')

In [51]:
device3 = "cuda" if torch.cuda.is_available() else "cpu"
device3

'cuda'

In [52]:
d = t.to(device1) #to shift at GPU
d

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [53]:
d = t.to(device2)
d

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [54]:
d = t.to(device3)
d

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [55]:
e = d.cpu() #to comeback at at CPU
e

tensor([[1, 2, 3],
        [4, 5, 6]])