<h2>Get GPU Details</h2>

In [4]:
!nvidia-smi

Fri May 30 12:39:24 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.19                 Driver Version: 561.19         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce MX130         WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A    0C    P0             N/A /  200W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch

In [3]:
torch.cuda.is_available() #to check GPU (it will return true if available else false)

True

In [16]:
print("GPU Name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU detected")

GPU Name: NVIDIA GeForce MX130


In [15]:
torch.cuda.device_count() #to count available GPUs

1

<h2>Work with GPU</h2>

In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
t = torch.tensor([[1,2,3],[4,5,6]])
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
d = t.to(device) #to load at GPU
d

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [9]:
e = d.cpu() #to comeback at at CPU
e

tensor([[1, 2, 3],
        [4, 5, 6]])