27:14 / 1:43:32

In [1]:
import torch

In [13]:
"""Numbers"""
s1 = torch.tensor(4) #Scaler value (this will return an integer number)
print(s1)
print(s1.dtype) #to check datatype

tensor(4)
torch.int64


In [14]:
s2 = torch.tensor(4.) #Scaler value (this will return a floating point number)
print(s2)
print(s2.dtype)

tensor(4.)
torch.float32


In [15]:
"""Vector"""
v1 = torch.tensor([1,2,3,4,5]) #Vector value (this will return an integer number)
print(v1)
print(v1.dtype)

tensor([1, 2, 3, 4, 5])
torch.int64


In [16]:
v2 = torch.tensor([1.,2,3,4,5]) #Vector value (this will return a floating point number). it converts all numbers into float if 1 number is float
print(v2)
print(v2.dtype)

tensor([1., 2., 3., 4., 5.])
torch.float32


In [18]:
"""Matrix"""
m1 = torch.tensor([[1,2,3],[4,5,6]]) #Matrix value (this will return an integer matrix)
print(m1)
print(m1.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64


In [19]:
m2 = torch.tensor([[1.,2,3],[4,5,6]]) #Matrix value (this will return a floating point number). it converts all numbers into float if 1 number is float
print(m2)
print(m2.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32


In [21]:
m3 = torch.tensor([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(m3.ndim)
print(m3)

3
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])


In [23]:
print(s1.shape)
print(v1.shape)
print(m2.shape)
print(m3.shape)

torch.Size([])
torch.Size([5])
torch.Size([2, 3])
torch.Size([3, 2, 3])


In [29]:
"""Tensor oprations and gradients"""
"""Creating Tensors"""
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5., requires_grad=True)

"""printing tensors"""
print(x)
print(w)
print(b)

tensor(3.)
tensor(4., requires_grad=True)
tensor(5., requires_grad=True)


In [31]:
"""Arithmetic operations"""
"""3 * 4 + 5 = 17"""
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [32]:
"""Compute derivatives"""
y.backward()

In [34]:
"""Display gradients"""
print(f"dy/dx: {x.grad}") #it wil return None because 'requires_grad' is not given
print(f"dy/dw: {w.grad}")
print(f"dy/db: {b.grad}")

dy/dx: None
dy/dw: 3.0
dy/db: 1.0


In [37]:
"""Create a tensor with a fixed value for every element"""
"""t1 = torch.full((row, column), item)"""
t1 = torch.full((3,2),42)
t1

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [42]:
"""Concatenate two tensor with compatible shape"""
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
z = torch.concat((x,y))
print(x+y)
print(z)

tensor([5, 7, 9])
tensor([1, 2, 3, 4, 5, 6])


In [44]:
torch.min(z) #to get minimum number

tensor(1)

In [45]:
torch.sin(z) #to get sin

tensor([ 0.8415,  0.9093,  0.1411, -0.7568, -0.9589, -0.2794])

In [46]:
z.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

Here's how we create an array in Numpy

In [47]:
import numpy as np

In [48]:
x = np.array([[1,2,4], [4,5,6]])
x

array([[1, 2, 4],
       [4, 5, 6]])

In [50]:
"""Convert the numpy array to a torch tensor"""
y = torch.from_numpy(x)
y

tensor([[1, 2, 4],
        [4, 5, 6]], dtype=torch.int32)

In [51]:
"""Convert a torch tensor to a numpy array"""
z = y.numpy()
z

array([[1, 2, 4],
       [4, 5, 6]])