In [1]:
inputs = [[1,2,3,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]

"""weights and biases for Layer1"""
weights = [[0.2,0.8,-0.5,1.0],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]
biases = [2,3,0.5]

In [3]:
import numpy as np

In [4]:
"""Layer1 example1"""
layer1 = np.dot(inputs, np.array(weights).T)+biases
layer1

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [7]:
print(f"Inputs: {inputs}")
print(f"Weights: {weights}")
print(f"Biases: {biases}")

Inputs: [[1, 2, 3, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
Weights: [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
Biases: [2, 3, 0.5]


In [9]:
weights = np.array(weights)
weights

array([[ 0.2 ,  0.8 , -0.5 ,  1.  ],
       [ 0.5 , -0.91,  0.26, -0.5 ],
       [-0.26, -0.27,  0.17,  0.87]])

In [11]:
transpose = weights.T
transpose

array([[ 0.2 ,  0.5 , -0.26],
       [ 0.8 , -0.91, -0.27],
       [-0.5 ,  0.26,  0.17],
       [ 1.  , -0.5 ,  0.87]])

In [13]:
"""Layer1 example2"""
l1 = np.dot(inputs,transpose)+biases
l1

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [15]:
"""weights and biases for layer2"""
weights2 = [[0.1,-0.14,0.5],
            [-0.5,0.12,-0.33],
            [-0.44,0.73,-0.13]]
biases2 = [-1,2,-0.5]

In [17]:
layer2 = np.dot(layer1,np.array(weights2).T)+biases2
layer2

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [19]:
"""Create a neuralNetwork layer"""
X = [[1,2,3,2.5],
     [2.0,5.0,-1.0,2.0],
     [-1.5,2.7,3.3,-0.8]]

In [52]:
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.biases

class Activation_ReLU:
    def forward(self,inputs):
        self.output = np.maximum(0,inputs)

In [74]:
np.random.seed(0)

layer1 = Layer_Dense(4,5)
relu = Activation_ReLU()
layer2 = Layer_Dense(5,2)
relu = Activation_ReLU()

layer1.forward(X)
l1 = layer1.output
print(l1)
print()

relu.forward(l1)
l1 = relu.output
print(l1)
print()

layer2.forward(l1)
l2 = layer2.output
print(l2)
print()

relu.forward(l2)
l2 = relu.output
print(l2)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]

[[0.10758131 1.03983522 0.24462411 0.31821498 0.18851053]
 [0.         0.70846411 0.00293357 0.44701525 0.36360538]
 [0.         0.55688422 0.07987797 0.         0.04553042]]

[[ 0.148296   -0.08397602]
 [ 0.1196862  -0.0079471 ]
 [ 0.07324824 -0.04625712]]

[[0.148296   0.        ]
 [0.1196862  0.        ]
 [0.07324824 0.        ]]


In [38]:
np.random.seed(0)
np.random.randn(4,3)

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351]])

In [40]:
np.random.seed(0)
0.10*np.random.randn(4,3)

array([[ 0.17640523,  0.04001572,  0.0978738 ],
       [ 0.22408932,  0.1867558 , -0.09772779],
       [ 0.09500884, -0.01513572, -0.01032189],
       [ 0.04105985,  0.01440436,  0.14542735]])

In [42]:
np.zeros((1,4))

array([[0., 0., 0., 0.]])