In [1]:
import numpy as np

<h1>Activation Functions</h1>

<h2>reLU (Rectified Linear Unit) Activation Function</h2>

<p>
    If your input is positive or zero, the output is the same as the input. If your input in negative, the output is zero.
</p>

In [4]:
inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
inputs

[0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]

<h3>example1</h3>

In [6]:
output1 = []
for i in inputs:
    if i > 0:
        output1.append(i)
    elif i <= 0:
        output1.append(0)
output1

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]

<h3>example2</h3>

In [8]:
output2 = []
for i in inputs:
    output2.append(max(0,i))
output2

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]

<h3>example3</h3>

In [10]:
output3 = np.maximum(0,inputs)
output3

array([0. , 2. , 0. , 3.3, 0. , 1.1, 2.2, 0. ])

<h2>Sofmax Activation Function</h2>

<h3>Input => Exponentiate => Normalization => Output</h3>

<img src="../pics/examples/04_softmax.jpg" width=300>

In [57]:
inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]

<h3>Exponentiation</h3>

In [15]:
ex = np.exp(inputs)
ex

array([1.00000000e+00, 7.38905610e+00, 3.67879441e-01, 2.71126389e+01,
       6.72055127e-02, 3.00416602e+00, 9.02501350e+00, 3.72007598e-44])

<h3>Normlization</h3>

In [40]:
norm_base = sum(ex)
norm_value = []
for value in inputs:
    norm_value.append(value/norm_base)

In [42]:
print(norm_base)
print(norm_value)

47.96595949688028
[0.0, 0.04169623668489485, -0.020848118342447423, 0.0687987905300765, -0.05628991952460805, 0.02293293017669217, 0.04586586035338434, -2.0848118342447424]


<h3>Complete softmaxActivation function</h3>

In [50]:
def softmaxActivation(arg):
    ex = np.exp(arg)
    norm_base = sum(ex)
    norm_value = []
    for value in arg:
        norm_value.append(value/norm_base)
    return norm_value

In [52]:
print(softmaxActivation(inputs))

[0.0, 0.04169623668489485, -0.020848118342447423, 0.0687987905300765, -0.05628991952460805, 0.02293293017669217, 0.04586586035338434, -2.0848118342447424]


<h2>Binary Sigmoid Activation Function<h2>

<p>
    Imagine you have a number. You want to squish that number into a value between 0 and 1. The Sigmoid function does just that. It's like putting a number through a machine that always gives you a result between 0 and 1.
</p>

In [76]:
inputs = np.array([0,2,-1,3.3,-2.7,1.1,2.2,-100])

<h3>example1</h3>

In [85]:
x = np.e**-inputs
y = 1+x
z = 1/y
z

array([5.00000000e-01, 8.80797078e-01, 2.68941421e-01, 9.64428811e-01,
       6.29733561e-02, 7.50260106e-01, 9.00249511e-01, 3.72007598e-44])

<h3>example2</h3>

In [95]:
j = 1/(1+np.e**-inputs)
j

array([5.00000000e-01, 8.80797078e-01, 2.68941421e-01, 9.64428811e-01,
       6.29733561e-02, 7.50260106e-01, 9.00249511e-01, 3.72007598e-44])

<h3>Complete Sigmoid activation function</h3>

In [99]:
def sigmoid(arg):
    return 1/(1+np.exp(-arg))

In [93]:
sigmoid(inputs)

array([5.00000000e-01, 8.80797078e-01, 2.68941421e-01, 9.64428811e-01,
       6.29733561e-02, 7.50260106e-01, 9.00249511e-01, 3.72007598e-44])