In [2]:
"""functions for creating arrays"""
"""
using arange function
=====================
arange is an array valued version of the built-in python range function
"""
import numpy as np

a = np.arange(10)
a #to print array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a = np.arange(1,10,2) #start, end, step
a

array([1, 3, 5, 7, 9])

In [4]:
"""using linspace"""
a = np.linspace(0,1,6) #start, end, number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [7]:
"""using ones (one cross one)"""
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
"""using zeros (3 cross 3)"""
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
"""using eye (3 cross 3)"""
c = np.eye(3) #returns a 2D array with ones on the diagonal and zeros elsewhere.
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
"""2 cross 2"""
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [14]:
e = np.eye(3,2) #3 number of rows, 2 is number of columns, index is diagonal start with 0
e

array([[1., 0.],
       [0., 1.],
       [0., 0.]])