In [1]:
import torch

Introduction to Tensor

Creating Tensor

In [2]:
a = torch.tensor(120) #Scaler value (0 Rank Tensor)
a

tensor(120)

to check the rank of tensor

In [3]:
a.ndim #0 Rank tensor

0

In [4]:
a+4

tensor(124)

to get the value from tensor

In [10]:
a.item() #this will give you element out of tensor (it will accept only scaler value)

120

In [7]:
b = torch.tensor([1,2,3]) #Vector value (1 Rank Tensor)
b

tensor([1, 2, 3])

In [8]:
b.ndim #1 Rank tensor

1

In [12]:
c = torch.tensor([[1,2,3],[4,5,6]]) #Matrix value (2 rank Tensor)
c

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
c.ndim #2 Rank tensor (We can know rank by just counting opening brackets "[")

2

Operations of Tensor

Creating a random Tensor

In [15]:
torch.rand(1)

tensor([0.3275])

In [17]:
torch.rand(4) #This all random values will be between 0 and 1

tensor([0.3739, 0.9686, 0.1258, 0.5545])

torch.rand((row,column))

In [20]:
torch.rand(3,4)

tensor([[0.3758, 0.5907, 0.1207, 0.7297],
        [0.8864, 0.7655, 0.0621, 0.1909],
        [0.4096, 0.6125, 0.2494, 0.8800]])

In [21]:
torch.rand(3,2,4)

tensor([[[0.4082, 0.6406, 0.8183, 0.5529],
         [0.1454, 0.8917, 0.1855, 0.6185]],

        [[0.1168, 0.5997, 0.3913, 0.3139],
         [0.2742, 0.8285, 0.4723, 0.5946]],

        [[0.4276, 0.6429, 0.2280, 0.8797],
         [0.7086, 0.8396, 0.1828, 0.8965]]])

Manual_seed => to reproduce the same random number

In [25]:
torch.manual_seed(777) #it returns a fix value for everyone
torch.rand(4)

tensor([0.0819, 0.4911, 0.4033, 0.3859])

In [26]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
torch.zeros(2,4,dtype=int)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [28]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
torch.ones(2,4,dtype=int)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])