In [2]:
import torch

In [3]:
a = torch.tensor(5)
b = torch.tensor(2)
a+b

tensor(7)

In [4]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

Addition

In [5]:
t+10

tensor([11, 12, 13])

In [6]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
t1+t2

tensor([5, 7, 9])

Subtraction

In [7]:
t3 = torch.tensor([1,2,3])
t4 = torch.tensor([4,5,6])
t4-1

tensor([3, 4, 5])

In [8]:
t4-t3

tensor([3, 3, 3])

Multiplication

In [9]:
t5 = torch.tensor([1,2,3])
t6 = torch.tensor([4,5,6])
t5*2

tensor([2, 4, 6])

In [10]:
t5*t6

tensor([ 4, 10, 18])

Functions

In [11]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

torch.randint(start,stop, (row, column))

In [13]:
r = torch.randint(1,100,(2,4))
r

tensor([[98, 83, 56, 71],
        [14, 83, 97, 73]])

In [14]:
r.min() #to get minimum value

tensor(14)

In [15]:
r.max() #to get maximum value

tensor(98)

In [16]:
r.sum()

tensor(575)

In [17]:
s = torch.arange(1,10+1)
s

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
s.sum()

tensor(55)

Mean value

In [26]:
m = s.type(torch.float) #to change datatype
torch.mean(m)

tensor(5.5000)

In [28]:
s.argmin() #returns index value

tensor(0)

In [29]:
s.argmax() #returns index value

tensor(9)

Reshape

In [34]:
w = torch.tensor([1,2,3,4,5])
w

tensor([1, 2, 3, 4, 5])

In [35]:
w.reshape(5,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5]])

In [30]:
x = torch.tensor([[1,2,3,4,5],[6,7,8,9,10]])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [33]:
x.reshape(5,2)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])