In [1]:
import torch

Indexing

In [4]:
m = torch.tensor([[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,14]])
m

tensor([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10],
        [10, 11, 12, 14]])

5,6<br>8,9<br>
m[1:3, 1:3]

In [8]:
m[1:3,1:3]

tensor([[5, 6],
        [8, 9]])

9,10<br>
12,14<br>
m[2:4, 2:4]

In [9]:
m[2:4, 2:4]

tensor([[ 9, 10],
        [12, 14]])

squeeze

In [11]:
m2 = torch.randint(10,30, (1,9))
m2

tensor([[12, 19, 27, 24, 15, 17, 14, 20, 19]])

In [13]:
print(m2.ndim)
print(m2.shape)

2
torch.Size([1, 9])


In [24]:
s = m2.squeeze()
s

tensor([12, 19, 27, 24, 15, 17, 14, 20, 19])

In [25]:
print(s.ndim)
print(s.shape)

1
torch.Size([9])


Converting PyTorch Tensor and Numpy Array

In [26]:
import numpy as np

In [29]:
n1 = np.arange(1,11)
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
t1 = torch.tensor(n1) #to convert numpy array into pytorch tensor
t1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=torch.int32)

In [32]:
t2 = torch.from_numpy(n1) #to convert numpy array into pytorch tensor
t2

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=torch.int32)

In [34]:
n2 = t2.numpy() #to convert pytorch tensor into numpy array
n2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Putting your tensor on GPU

!nvidia-smi #to check GPU version

In [41]:
!nvidia-smi

Sun Feb 11 13:38:00 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.26                 Driver Version: 546.26       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce MX130         WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P0              N/A / 200W |      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [43]:
torch.cuda.is_available() #it will return True if GPU found

True

In [46]:
torch.cuda.device_count() #to cound available GPU's

1

In [47]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [48]:
m4 = torch.tensor([[1,2,3],[4,5,6]])
m4

tensor([[1, 2, 3],
        [4, 5, 6]])

In [52]:
d = m4.to(device) #to load at GPU
d

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [56]:
c = d.cpu() #to takeback at CPU
c

tensor([[1, 2, 3],
        [4, 5, 6]])