In [15]:
inputs = [[1,2,3,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]

"""weights and biases for Layer1"""
weights = [[0.2,0.8,-0.5,1.0],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]
biases = [2,3,0.5]

In [31]:
import numpy as np

In [33]:
"""Layer1 example1"""
layer1 = np.dot(inputs, np.array(weights).T)+biases
layer1

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [35]:
print(f"Inputs: {inputs}")
print(f"Weights: {weights}")
print(f"Biases: {biases}")

Inputs: [[1, 2, 3, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
Weights: [[ 0.2   0.8  -0.5   1.  ]
 [ 0.5  -0.91  0.26 -0.5 ]
 [-0.26 -0.27  0.17  0.87]]
Biases: [2, 3, 0.5]


In [37]:
weights = np.array(weights)
weights

array([[ 0.2 ,  0.8 , -0.5 ,  1.  ],
       [ 0.5 , -0.91,  0.26, -0.5 ],
       [-0.26, -0.27,  0.17,  0.87]])

In [39]:
transpose = weights.T
transpose

array([[ 0.2 ,  0.5 , -0.26],
       [ 0.8 , -0.91, -0.27],
       [-0.5 ,  0.26,  0.17],
       [ 1.  , -0.5 ,  0.87]])

In [43]:
"""Layer1 example2"""
l1 = np.dot(inputs,transpose)+biases
l1

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [45]:
"""weights and biases for layer2"""
weights2 = [[0.1,-0.14,0.5],
            [-0.5,0.12,-0.33],
            [-0.44,0.73,-0.13]]
biases2 = [-1,2,-0.5]

In [49]:
layer2 = np.dot(layer1,np.array(weights2).T)+biases2
layer2

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [89]:
"""Designing a neuralNetwork layer"""
X = [[1,2,3,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]

In [95]:
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.biases

In [103]:
layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
print(layer1.output)

layer2.forward(layer1.output)
print(layer2.output)

[[ 0.47538406 -0.21561014  0.15471002  0.00969772  0.23743679]
 [ 0.74538019 -1.33493975  0.06268022 -0.13968264  0.36648785]
 [ 0.20221943 -0.15138846  0.19657628  0.05843791 -0.27192329]]
[[-0.04460662  0.06396692]
 [-0.10021778  0.07334713]
 [-0.0023019   0.03089178]]


In [63]:
np.random.randn(4,3)

array([[ 0.57361758,  0.09559601,  1.04477441],
       [ 0.41329841, -1.45493485, -0.59762755],
       [-0.24012071, -0.03890405,  0.76933719],
       [ 0.28641382,  0.70501453, -0.65738575]])

In [65]:
0.10*np.random.randn(4,3)

array([[ 0.01564233, -0.11708167,  0.01326962],
       [-0.01004384, -0.04160786,  0.08235483],
       [-0.0109072 , -0.19674653,  0.0438091 ],
       [-0.05710462, -0.02212962, -0.0572087 ]])

In [69]:
np.zeros((1,4))

array([[0., 0., 0., 0.]])