In [23]:
import pandas as pd #pip install pandas

In [24]:
df = pd.read_csv("exe_file.csv")
df

Region  Temp. (F)  Rainfall (mm)  Humidity (%)  Apples (ton)  Oranges (ton)
0   Kanto         73             67            43            56             70
1   Johto         91             88            64            81            101
2   Hoenn         87            134            58           119            133
3  Sinnoh        102             43            37            22             37
4   Vnova         69             96            70           103            119

In [25]:
import numpy as np

<h2>Assigning featuress</h2>

In [26]:
"""inputs = (temp, rainfall, humidity)"""
inputs = np.array([
    [73,67,43],
    [91,88,64],
    [87,134,58],
    [102,43,37],
    [69,96,70]
    ], dtype="float32")

inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

<h1>Assigning targets</h2>

In [27]:
"""targets=(apples,oranges)"""
targets = np.array([
    [56,70],
    [81,101],
    [119, 133],
    [22,37],
    [103, 119]
], dtype="float32")

targets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

<h2>Convert inputs, and targets into tensor</h2>

In [28]:
import torch

In [29]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs)
print()
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


<h2>set weights and biases</h2>

In [30]:
w = torch.randn(2,3, requires_grad=True) #weights
b = torch.randn(2, requires_grad=True) #biases

print(w)
print()
print(b)

tensor([[ 1.0772, -0.1121,  0.2155],
        [-0.4210,  0.5061,  1.1195]], requires_grad=True)

tensor([-0.6403, -2.4576], requires_grad=True)


<h2>Transform weights</h2>

In [33]:
wt = w.t()
wt

tensor([[ 1.0772, -0.4210],
        [-0.1121,  0.5061],
        [ 0.2155,  1.1195]], grad_fn=<TBackward0>)

<h2>Multiply inputs with weights</h2>

In [34]:
x = inputs @ wt
x

tensor([[ 80.3932,  51.3186],
        [101.9546,  77.8797],
        [ 91.1944,  96.1282],
        [113.0314,  20.2460],
        [ 78.6513,  97.9075]], grad_fn=<MmBackward0>)

<h2>Add biases</h2>

In [36]:
x += b
x

tensor([[ 79.1126,  46.4034],
        [100.6740,  72.9646],
        [ 89.9138,  91.2130],
        [111.7508,  15.3308],
        [ 77.3707,  92.9923]], grad_fn=<AddBackward0>)

<h2>Transform, Multiply, and Add in oneline</h2>

In [37]:
x = inputs @ w.t() + b
x

tensor([[ 79.7529,  48.8610],
        [101.3143,  75.4221],
        [ 90.5541,  93.6706],
        [112.3911,  17.7884],
        [ 78.0110,  95.4499]], grad_fn=<AddBackward0>)

<h2>Put all calculations into a function</h2>

In [38]:
def model(x):
    return x @ w.t() + b

<h2>Generate predictions</h2>

In [39]:
preds = model(inputs)
print(preds)

tensor([[ 79.7529,  48.8610],
        [101.3143,  75.4221],
        [ 90.5541,  93.6706],
        [112.3911,  17.7884],
        [ 78.0110,  95.4499]], grad_fn=<AddBackward0>)


<h2>Compare with targets</h2>

In [41]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


<h1>Loss function</h1>

In [43]:
diff = preds - targets #to calculate loss
diff

tensor([[ 23.7529, -21.1390],
        [ 20.3143, -25.5779],
        [-28.4459, -39.3294],
        [ 90.3911, -19.2116],
        [-24.9890, -23.5501]], grad_fn=<SubBackward0>)

<h2>Remove negative values</h2>

In [44]:
diff *= diff
diff

tensor([[ 564.1984,  446.8565],
        [ 412.6717,  654.2264],
        [ 809.1701, 1546.8010],
        [8170.5449,  369.0846],
        [ 624.4515,  554.6073]], grad_fn=<MulBackward0>)

In [46]:
s = torch.sum(diff) #to sum of all diff elements
s

tensor(14152.6123, grad_fn=<SumBackward0>)

In [48]:
print(diff.numel()) #to get diff element's count

10


In [49]:
s / diff.numel() #to get average

tensor(1415.2612, grad_fn=<DivBackward0>)

<h2>All codes in oneline</h2>

In [50]:
diff = preds - targets
torch.sum(diff*diff)/diff.numel()

tensor(1415.2612, grad_fn=<DivBackward0>)

<h1>Define MSE (Mean Square Error) function</h1>

In [51]:
def mse(t1,t2):
    diff = t1 - t2
    return torch.sum(diff*diff)/diff.numel()

<h2>Compare loss</h2>

In [52]:
loss = mse(preds, targets)
print(loss)

tensor(1415.2612, grad_fn=<DivBackward0>)
