In [58]:
import torch as t

In [59]:
x = t.empty(1) #1D
x

tensor([3.5873e-43])

In [60]:
x = t.rand(1) #1D
x

tensor([0.7940])

In [61]:
x = t.empty(5,3) #2D
x

tensor([[ 1.4013e-45,  0.0000e+00,  0.0000e+00],
        [-7.3487e+14,  2.2030e-20, -1.5817e+10],
        [ 1.7810e-17, -1.4377e-42, -3.8736e-03],
        [ 4.5908e-41,  0.0000e+00,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00,  0.0000e+00]])

In [62]:
x = t.empty(2,5,3) #3D
x

tensor([[[1.4013e-45, 0.0000e+00, 9.9601e-35],
         [6.6702e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 1.6922e+25],
         [6.6702e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])

In [63]:
x = t.empty(2,2,5,3) #4D
x

tensor([[[[ 3.5598e-34,  6.6702e-43,  3.5599e-34],
          [ 6.6702e-43, -3.7793e-05,  4.5908e-41],
          [-3.7793e-05,  4.5908e-41,  7.8889e-35],
          [ 6.6702e-43,  2.9120e-36,  6.6702e-43],
          [ 7.8890e-35,  6.6702e-43,  3.5599e-34]],

         [[ 6.6702e-43,  3.5599e-34,  6.6702e-43],
          [-3.7793e-05,  4.5908e-41,  3.6191e-34],
          [ 6.6702e-43,  3.6191e-34,  6.6702e-43],
          [ 7.8890e-35,  6.6702e-43,  7.8891e-35],
          [ 6.6702e-43, -3.7793e-05,  4.5908e-41]]],


        [[[ 3.6191e-34,  6.6702e-43,  3.6059e-34],
          [ 6.6702e-43,  2.9103e-36,  6.6702e-43],
          [-3.7793e-05,  4.5908e-41, -3.7793e-05],
          [ 4.5908e-41,  3.5599e-34,  6.6702e-43],
          [ 3.5599e-34,  6.6702e-43,  3.5600e-34]],

         [[ 6.6702e-43,  2.9105e-36,  6.6702e-43],
          [-3.7793e-05,  4.5908e-41, -3.7793e-05],
          [ 4.5908e-41,  3.5600e-34,  6.6702e-43],
          [ 3.6192e-34,  6.6702e-43,  3.6059e-34],
          [ 6.6702e-43,

In [64]:
x = t.zeros(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [65]:
x = t.ones(5,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [66]:
x = t.rand(1,2)
y = t.rand(2,2)
z = x+y

In [67]:
x

tensor([[0.5483, 0.7292]])

In [68]:
y

tensor([[0.4583, 0.1062],
        [0.2540, 0.8316]])

In [69]:
z

tensor([[1.0066, 0.8354],
        [0.8023, 1.5608]])

In [70]:
x = t.rand(5,2)
x

tensor([[0.2453, 0.7188],
        [0.7593, 0.3908],
        [0.1705, 0.4381],
        [0.6888, 0.1356],
        [0.4252, 0.3395]])

In [71]:
y = x.view(10) #to convert into 1D (the number should be == all element of x) like reshape in numpy
y

tensor([0.2453, 0.7188, 0.7593, 0.3908, 0.1705, 0.4381, 0.6888, 0.1356, 0.4252,
        0.3395])

In [72]:
y = x.view(-1,5) #to make 2D array
y

tensor([[0.2453, 0.7188, 0.7593, 0.3908, 0.1705],
        [0.4381, 0.6888, 0.1356, 0.4252, 0.3395]])

In [73]:
x = t.rand(2,6)
x

tensor([[0.3813, 0.3286, 0.4848, 0.4822, 0.9881, 0.2212],
        [0.7930, 0.0206, 0.6274, 0.3428, 0.0064, 0.2200]])

In [74]:
y = x.view(3,4)
y

tensor([[0.3813, 0.3286, 0.4848, 0.4822],
        [0.9881, 0.2212, 0.7930, 0.0206],
        [0.6274, 0.3428, 0.0064, 0.2200]])