In [1]:
import torch as tr
import numpy as np

In [4]:
"""convert array into tensor"""
x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [6]:
y = tr.from_numpy(x) #to convert into tensor
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [7]:
x.dtype, y.dtype

(dtype('int32'), torch.int32)

In [8]:
"""convet tensor into array"""
a = tr.ones(2,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
b = a.numpy() #to convert into array
b

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [11]:
a.dtype, b.dtype

(torch.float32, dtype('float32'))