In [1]:
import torch as t

In [3]:
if t.cuda.is_available():
    device = t.device("cuda")
else:
    device = t.device("cpu")
    
device

device(type='cuda')

In [4]:
y = t.ones(5,3, device=device)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [5]:
x = t.ones(5,3, device="cpu")
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
x = x.to(device) #to shift into gpu
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [11]:
y = t.ones(4,5, device="cuda")
y

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')

In [16]:
import torch
torch.cuda.is_available()

True