In [1]:
import torch

In [2]:
x = torch.empty(1) #to create a 1D tensor with single element
x

tensor([0.])

In [4]:
x = torch.empty(3) #to create 1D tensor with multiple elements
x

tensor([0., 0., 0.])

In [5]:
x = torch.empty(2,3) #to create 2D tensor
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
x = torch.empty(2,3,2) #to create 3D tensor
x

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [7]:
x = torch.rand(2) #to create tensors with random value
x

tensor([0.6247, 0.0753])

In [8]:
x = torch.rand(2,3)
x

tensor([[0.8545, 0.7374, 0.5095],
        [0.7178, 0.9460, 0.2187]])

In [9]:
x = torch.zeros(3)
x

tensor([0., 0., 0.])

In [10]:
x = torch.zeros(3,2)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
x = torch.ones(1)
x

tensor([1.])

In [12]:
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
x.dtype

torch.float32

In [15]:
x = torch.ones(2,3, dtype=torch.int)
x

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [16]:
x = torch.ones(2,3, dtype=torch.int16)
x

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [17]:
x.dtype

torch.int16

In [18]:
x.size()

torch.Size([2, 3])

In [20]:
x = torch.tensor([[1,2,4,6],[4,6,3,8]])
x

tensor([[1, 2, 4, 6],
        [4, 6, 3, 8]])

In [21]:
x = torch.tensor([1,2,4,6])
y = torch.tensor([5,7,2,9])

In [22]:
z = x+y
z

tensor([ 6,  9,  6, 15])

In [23]:
z = torch.add(x,y)
z

tensor([ 6,  9,  6, 15])

In [24]:
x = torch.tensor([1,2,3,4])
y = torch.tensor([5,6,7,8])

In [25]:
z = x-y
z

tensor([-4, -4, -4, -4])

In [26]:
z = torch.sub(y,x)
z

tensor([4, 4, 4, 4])

In [25]:
#y.add_(x) # for inline operation
#y

In [26]:
z = x*y
z

tensor([ 5, 12, 21, 32])

In [27]:
z = torch.mul(x,y)
z

tensor([ 5, 12, 21, 32])

In [28]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
x[0,:]

tensor([1, 2, 3])

In [30]:
x[1,:]

tensor([4, 5, 6])

In [31]:
x[:,0]

tensor([1, 4, 7])

x[:,1]

In [32]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [33]:
x[1].item()

2

<h1>Reshaping</h1>

In [35]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
y = x.view(9) #to convert into 1D
y

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
y = x.view(-1,3) #3 is number of columns (columns should be equal devided)
y

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [38]:
y = x.view(-1,1)
y

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [39]:
x.size()

torch.Size([3, 3])

In [42]:
x = torch.tensor([[1,2,3,4],[5,3,2,1]])
x

tensor([[1, 2, 3, 4],
        [5, 3, 2, 1]])

In [43]:
x.dtype

torch.int64

<h1>Change data bit</h1>

In [47]:
x32 = torch.tensor(x, dtype=torch.float32)
x32, x32.dtype

C:\Users\Abdul Zoha\AppData\Local\Temp\ipykernel_6912\2201978412.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x32 = torch.tensor(x, dtype=torch.float32)


(tensor([[1., 2., 3., 4.],
         [5., 3., 2., 1.]]),
 torch.float32)

In [50]:
x32b = x.to(dtype=torch.float32)
x32b, x32b.dtype

(tensor([[1., 2., 3., 4.],
         [5., 3., 2., 1.]]),
 torch.float32)

In [52]:
tensor1 = x.float() #32bit
tensor1, tensor1.dtype

(tensor([[1., 2., 3., 4.],
         [5., 3., 2., 1.]]),
 torch.float32)

In [53]:
tensor2 = tensor1.double() #64bit
tensor2, tensor2.dtype

(tensor([[1., 2., 3., 4.],
         [5., 3., 2., 1.]], dtype=torch.float64),
 torch.float64)

<h1>Convert into numpy or vise-versa</h1>

In [39]:
import numpy as np

In [43]:
a = t.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(type(a))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
<class 'torch.Tensor'>


In [44]:
b = a.numpy() #to convert into numpy
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [45]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(type(c))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [46]:
d = t.from_numpy(b) #to convert into tensor
print(d)
print(type(d))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
<class 'torch.Tensor'>


<h1>Use GPU</h1>

In [57]:
"Example-1"
if t.cuda.is_available():
  device = t.device("cuda")
  x = t.tensor([[1,2,3],[4,5,6],[7,8,9]], device=device) #to create and run at GPU
  print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='cuda:0')


In [58]:
"Example-2"
y = t.tensor([[1,2,3],[4,5,6],[7,8,9]])
y

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [59]:
y = y.to(device) #to run at GPU
y

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='cuda:0')