In [2]:
import torch as t

In [3]:
x = t.empty(1) #to create a 1D tensor with single element
x

tensor([1.8164e-23])

In [4]:
x = t.empty(3) #to create 1D tensor with multiple elements
x

tensor([1.8165e-23, 4.3194e-41, 1.8165e-23])

In [5]:
x = t.empty(2,3) #to create 2D tensor
x

tensor([[ 1.8165e-23,  4.3194e-41, -1.3396e-27],
        [ 3.1924e-41,  4.4842e-44,  0.0000e+00]])

In [6]:
x = t.empty(2,3,2) #to create 3D tensor
x

tensor([[[1.8165e-23, 4.3194e-41],
         [1.8165e-23, 4.3194e-41],
         [4.4842e-44, 0.0000e+00]],

        [[1.5695e-43, 0.0000e+00],
         [2.5110e-21, 3.1920e-41],
         [0.0000e+00, 0.0000e+00]]])

In [7]:
x = t.rand(2) #to create tensors with random value
x

tensor([0.5103, 0.9680])

In [8]:
x = t.rand(2,3)
x

tensor([[0.7980, 0.7892, 0.7777],
        [0.6250, 0.0816, 0.3810]])

In [9]:
x = t.zeros(3)
x

tensor([0., 0., 0.])

In [10]:
x = t.zeros(3,2)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
x = t.ones(1)
x

tensor([1.])

In [12]:
x = t.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
x.dtype

torch.float32

In [14]:
x = t.ones(2,3, dtype=t.int)
x

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [15]:
x = t.ones(2,3, dtype=t.int16)
x

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [16]:
x.dtype

torch.int16

In [17]:
x.size()

torch.Size([2, 3])

In [18]:
x = t.tensor([[1,2,4,6],[4,6,3,8]])
x

tensor([[1, 2, 4, 6],
        [4, 6, 3, 8]])

In [19]:
x = t.tensor([1,2,4,6])
y = t.tensor([5,7,2,9])

In [20]:
z = x+y
z

tensor([ 6,  9,  6, 15])

In [21]:
z = t.add(x,y)
z

tensor([ 6,  9,  6, 15])

In [22]:
x = t.tensor([1,2,3,4])
y = t.tensor([5,6,7,8])

In [23]:
z = x-y
z

tensor([-4, -4, -4, -4])

In [24]:
z = t.sub(y,x)
z

tensor([4, 4, 4, 4])

In [25]:
#y.add_(x) # for inline operation
#y

In [26]:
z = x*y
z

tensor([ 5, 12, 21, 32])

In [27]:
z = t.mul(x,y)
z

tensor([ 5, 12, 21, 32])

In [28]:
x = t.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
x[0,:]

tensor([1, 2, 3])

In [30]:
x[1,:]

tensor([4, 5, 6])

In [31]:
x[:,0]

tensor([1, 4, 7])

x[:,1]

In [32]:
x = t.tensor([1,2,3])
x

tensor([1, 2, 3])

In [33]:
x[1].item()

2

<h1>Reshaping</h1>

In [34]:
x = t.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [35]:
y = x.view(9) #to convert into 1D
y

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
y = x.view(-1,3) #3 is number of columns (columns should be equal devided)
y

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [37]:
y = x.view(-1,1)
y

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [38]:
x.size()

torch.Size([3, 3])

<h1>Convert into numpy or vise-versa</h1>

In [39]:
import numpy as np

In [43]:
a = t.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(type(a))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
<class 'torch.Tensor'>


In [44]:
b = a.numpy() #to convert into numpy
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [45]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(type(c))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [46]:
d = t.from_numpy(b) #to convert into tensor
print(d)
print(type(d))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
<class 'torch.Tensor'>


<h1>Use GPU</h1>

In [57]:
"Example-1"
if t.cuda.is_available():
  device = t.device("cuda")
  x = t.tensor([[1,2,3],[4,5,6],[7,8,9]], device=device) #to create and run at GPU
  print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='cuda:0')


In [58]:
"Example-2"
y = t.tensor([[1,2,3],[4,5,6],[7,8,9]])
y

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [59]:
y = y.to(device) #to run at GPU
y

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='cuda:0')