In [1]:
import numpy as np

a = np.random.randint(0,20,15)
print(a)

[ 2 13 17  4 11 13 13  0  5 10  1  2 12 14  6]


In [3]:
mask = (a % 2 == 0)

In [4]:
extract_from_a = a[mask]
print(extract_from_a)

[ 2  4  0 10  2 12 14  6]


In [5]:
"""indexing with a mask can be very useful to assign a new value to a sub-array"""
a[mask] = -1
print(a)

[-1 13 17 -1 11 13 13 -1  5 -1  1 -1 -1 -1 -1]


In [6]:
"""indexing with an array of integers"""
a = np.arange(0,100,10)
print(a)

[ 0 10 20 30 40 50 60 70 80 90]


In [9]:
"""indexing can be done with an array of integers, where the same index is repeated several times"""
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [12]:
"""new values can be assigned"""
a[[9,7]] = -200
print(a)

[   0   10   20   30   40   50   60 -200   80 -200]
