In [1]:
import numpy as np

In [10]:
a = np.tile(np.arange(0, 40, 10), (4,1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [24]:
a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [27]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [26]:
a + b

ValueError: operands could not be broadcast together with shapes (4,4) (3,) 