In [1]:
import numpy as np

In [2]:
"""flattening"""
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
b = a.ravel() #convert into 1D array
print(b)

[1 2 3 4 5 6]


In [4]:
c = a.T
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
d = c.ravel()
print(d)

[1 4 2 5 3 6]


In [6]:
"""reshaping"""
e = a.ravel()
print(e)
print()

b = e.reshape((2,3))
print(b)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]


In [7]:
b[0, 1] = 400 #change value (row, column)
print(b)

[[  1 400   3]
 [  4   5   6]]


In [8]:
a = np.zeros((3, 2))
print(a)
print()

b = a.T.reshape(3*2)
print(b)
print()

b.reshape(3*2)
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0.]


In [9]:
b[0] = 70
print(b)

[70.  0.  0.  0.  0.  0.]


In [12]:
z = np.array([1,2,3])
print(z)

[1 2 3]


In [15]:
b = z[:, np.newaxis]
print(b)

[[1]
 [2]
 [3]]


In [17]:
c = np.arange(4*3*2).reshape(4,3,2)
print(c)
print(c.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
(4, 3, 2)


In [11]:
"""1:01:00 / 1:06:54"""

'1:01:00 / 1:06:54'