In [1]:
import numpy as np

In [6]:
a = np.arange(4)
print(a)
a.resize(8,)
print(a)

[0 1 2 3]
[0 1 2 3 0 0 0 0]


In [9]:
"""sorting along an axis"""
a = np.array([[5,4,6], [2,3,2]])
print(a)
print()
b = np.sort(a, axis=1)
print(b)

[[5 4 6]
 [2 3 2]]

[[4 5 6]
 [2 2 3]]


In [10]:
a.sort(axis=1)
print(a)

[[4 5 6]
 [2 2 3]]


In [11]:
"""sorting with fancy indexing"""
a = np.array([4,3,1,2])
j = np.argsort(a)
print(j)

[2 3 1 0]
