1: np.array, 2: np.arange, 3: np.empty, 4: np.zeros, 5: np.ones, 6: np.linspace, 7: np.logspace, 8: np.full, 9: np.random.random

In [2]:
import numpy as np

In [3]:
myArr = np.array([1,2,3,4,5])
myArr

array([1, 2, 3, 4, 5])

In [4]:
myArr2 = np.arange(0,4) #start, end (end will be excluded)
myArr2

array([0, 1, 2, 3])

In [5]:
myArr3 = np.arange(0,10,2) #start, end, step
myArr3

array([0, 2, 4, 6, 8])

In [6]:
myArr4 = np.empty([2,4]) #2 rows, 4 columns
myArr4

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 7.17383318e-321, 1.05700345e-307,
        1.27941747e-307]])

In [7]:
myArr5 = np.zeros([2,4]) #2 rows, 4 columns
myArr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
myArr6 = np.ones([2,4])
myArr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
myArr7 = np.linspace(0,10,5) #start, end, space (to create array with linearspace)
myArr7

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
myArr8 = np.logspace(0,10,5)
myArr8

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

In [12]:
myArr9 = np.full((3,5), 14)
myArr9

array([[14, 14, 14, 14, 14],
       [14, 14, 14, 14, 14],
       [14, 14, 14, 14, 14]])