1: np.array, 2: np.arange, 3: np.empty, 4: np.zeros, 5: np.ones, 6: np.linspace, 7: np.logspace, 8: np.full, 9: np.random.random

In [2]:
import numpy as np

In [3]:
myArr = np.array([1,2,3,4,5])
myArr

array([1, 2, 3, 4, 5])

In [14]:
myArr = np.arange(4)
myArr

array([0, 1, 2, 3])

In [4]:
myArr2 = np.arange(0,4) #start, end (end will be excluded)
myArr2

array([0, 1, 2, 3])

In [5]:
myArr3 = np.arange(1,4)
myArr3

array([1, 2, 3])

In [6]:
myArr3 = np.arange(0,10,2) #start, end, step
myArr3

array([0, 2, 4, 6, 8])

In [7]:
myArr4 = np.empty([2,4]) #2 rows, 4 columns
myArr4

array([[0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 6.937e-321, 0.000e+000, 0.000e+000]])

In [8]:
myArr5 = np.zeros([2,4]) #2 rows, 4 columns
myArr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
myArr6 = np.ones([2,4]) #2 row, 4 columns
myArr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
myArr7 = np.linspace(0,10,5) #start, end, number of points (to create array with linearspace)
myArr7

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
myArr8 = np.logspace(0,10,5)
myArr8

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

In [15]:
"""identity function"""
e = np.eye(3) #returns a 2D array with one on the diagonal and zeros elsewhere.
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
f = np.eye(3,5) #3 is number of rows, 5 is number of columns, index of diagonal start with 0.
f

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [20]:
"""diag function"""
d = np.diag([1,2,3,4,5])
d

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [22]:
n = np.diag(d) #to extract diagonal
n

array([1, 2, 3, 4, 5])

In [12]:
myArr9 = np.full((3,5), 14)
myArr9

array([[14, 14, 14, 14, 14],
       [14, 14, 14, 14, 14],
       [14, 14, 14, 14, 14]])

In [24]:
"""random function"""
"""create an array of the given shape and populate it with random samples from a uniform distribution"""
a = np.random.rand(4)
a

array([0.57959933, 0.31368452, 0.11732011, 0.38363217])

In [26]:
a = np.random.randn(4) #return a sample (or samples) from the "standard normal" distribution (Gausian value)
a

array([-0.50375398,  2.46584364, -0.02396842,  1.82272761])