1: myArr.shape, 2: myArr.ndim, 3: myArr.dtype, 4: myArr.size, 5: myArr.ravel, 6: myArr.reshape, 7: myArr.sqrt, 8: np.where, 9: np.count_nonzero, 10: np.nonzero, 11: myArr.nbytes

In [44]:
import numpy as np

In [45]:
myArr = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]]) #3D array
myArr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [46]:
myArr.shape #to check shape

(2, 2, 3)

In [47]:
myArr.ndim #to chech dimensions

3

In [48]:
myArr.dtype #to check datatype

dtype('int32')

In [49]:
myArr.size #to check numbers of total elements

12

In [50]:
new_data = myArr.ravel() #to convert into 1D
new_data

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [51]:
new_data.reshape(2,6) #to change into 2D

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [52]:
myArr2 = np.array([0,4,0,6,0,5,8])
np.count_nonzero(myArr2) #to count nonzero elements

4

In [53]:
np.nonzero(myArr2) #to get index of nonzero elements

(array([1, 3, 5, 6], dtype=int64),)

In [54]:
myArr.nbytes #to check occupied bytesS

48

In [55]:
np.sqrt(myArr) #to make square root

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]]])

In [56]:
np.where(myArr<2) #to get index values that is greater than 2

(array([0, 1], dtype=int64),
 array([0, 0], dtype=int64),
 array([0, 0], dtype=int64))

In [57]:
np.zeros([2,4], dtype=int) #to set datatype

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [58]:
np.zeros([2,4], dtype=np.int8) #set datatype into int8

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)