In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
arr[0] #to fetch zero's index item

1

In [6]:
arr[1] #to fetch one's index item

2

In [9]:
arr[1] = 4 #to change arr's one's index item
arr

array([1, 4, 3])

In [11]:
"""example with 2D array"""
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2[0] #to access first array

array([1, 2, 3])

In [14]:
arr2[0][1] #to access first index item of first array

2

In [15]:
arr2[0,1] #to access first index item of first array

2

In [16]:
arr2[0,1]+arr2[1,1]

7