In [ ]:
"""
1D array:
    axis=0 #left to right (default)

2D array:
    axis=0 #up to down
    axis=1 #left to right

3D array:
    axis=0 #front to back
    axis=1 #up to down
    axis=2 #left to right
"""

In [1]:
import numpy as np

In [2]:
"""1D array math"""
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [4]:
arr1.sum() #to sum all array items "left to right" (axis=0) default

6

In [5]:
arr1.sum(axis=0)

6

In [6]:
"""2D array math"""
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr2.sum() #sum all the elements of array from "left to right"

21

In [11]:
arr2.sum(axis=0) #up to down

array([5, 7, 9])

In [12]:
arr2.sum(axis=1) #left to right

array([ 6, 15])

In [22]:
"""3D array math"""
arr3 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [23]:
arr3.sum(axis=0) #front to back

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [24]:
arr3.sum(axis=1) #up to down

array([[12, 15, 18],
       [12, 15, 18]])

In [25]:
arr3.sum(axis=2) #left to right

array([[ 6, 15, 24],
       [ 6, 15, 24]])

In [27]:
arr3.argmin(axis=0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [31]:
arr3.argmin(axis=1)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [32]:
arr3.argmin(axis=2)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [33]:
arr3.argmax(axis=0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [34]:
arr3.argmax(axis=1)

array([[2, 2, 2],
       [2, 2, 2]], dtype=int64)

In [36]:
arr3.argmax(axis=2)

array([[2, 2, 2],
       [2, 2, 2]], dtype=int64)