In [2]:
import numpy as np

In [3]:
"""range function"""
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
b = np.arange(0, 10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
c = np.arange(1,10)
print(c)

[1 2 3 4 5 6 7 8 9]


In [6]:
d = np.arange(1,10,2) #start, end, step
print(d)

[1 3 5 7 9]


In [7]:
"""linspace function"""
a = np.linspace(0,1,6) #start, end, number of points
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [8]:
"""ones function"""
b = np.ones((3,3))
c = np.ones((2,4))
print(b)
print()
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
"""zeros function"""
d = np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
"""identity function"""
e = np.eye(3) #returns a 2D array with one on the diagonal and zeros elsewhere.
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
f = np.eye(3,5) #3 is number of rows, 5 is number of columns, index of diagonal start with 0.
print(f)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [12]:
"""diag function"""
a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [13]:
n = np.diag(a) #to extract diagonal
print(n)

[1 2 3 4]


In [14]:
"""random function"""
"""create an array of the given shape and populate it with random samples from a uniform distribution"""
a = np.random.rand(4)
print(a)

[0.3327604  0.2476253  0.36220402 0.07461124]


In [15]:
a = np.random.randn(4) #return a sample (or samples) from the "standard normal" distrivution (Gausian value)
print(a)

[-1.3893175   0.90360872 -0.2432112  -0.71982749]


In [ ]:
"""18:00 / 1:06:54"""