In [2]:
import numpy as np

In [3]:
a = np.array([1,2,4,7,9])
print(a)

[1 2 4 7 9]


In [4]:
print(a[4])

9


In [11]:
b = np.diag([1,2,3])
print(b)
print()
print(b[2,2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]

3


In [15]:
"""assigning values"""
b[2,1] = 5
print(b)

[[1 0 0]
 [0 2 0]
 [0 5 3]]
