In [1]:
"""24:00 / 1:06:54"""

'24:00 / 1:06:54'

In [2]:
import numpy as np

In [12]:
a = np.arange(10) #startIndex, endIndex (exclusive), step
print(a)
b = a[1:8:2]
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [18]:
"""we can also combine assignment and slicing"""
a = np.arange(10)
a[5:] = 8 #put eight after fifth index
print(a)

[0 1 2 3 4 8 8 8 8 8]


In [28]:
"""reverse numbers"""
b = np.arange(5)
a[5:] = b[::-1]
print(a)
print()

c = np.arange(10)
print(c)
print()

c = c[::-1]
print(c)

[0 1 2 3 4 4 3 2 1 0]

[0 1 2 3 4 5 6 7 8 9]

[9 8 7 6 5 4 3 2 1 0]
