In [ ]:
"""35:00 / 1:06:54"""

In [3]:
import numpy as np

a = np.random.randint(0,20,15)
print(a)

[17  7  4  4 18  9 19 16  3  1 10  2  2  8  3]


In [4]:
mask = (a % 2 == 0)

In [5]:
extract_from_a = a[mask]
print(extract_from_a)

[ 4  4 18 16 10  2  2  8]


In [6]:
"""indexing with a mask can be very useful to assign a new value to a sub-array"""
a[mask] = -1
print(a)

[17  7 -1 -1 -1  9 19 -1  3  1 -1 -1 -1 -1  3]


In [8]:
"""indexing with an array of integers"""
a = np.arange(0,100,10)
print(a)

[ 0 10 20 30 40 50 60 70 80 90]


In [9]:
"""indexing can be done with an array of integers, where the same index is repeated several times"""
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [12]:
"""new values can be assigned"""
a[[9,7]] = -200
print(a)

[   0   10   20   30   40   50   60 -200   80 -200]
