In [1]:
import numpy as np

In [8]:
"""flattening"""
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [9]:
b = a.ravel() #convert into 1D array
print(b)

[1 2 3 4 5 6]


In [19]:
c = a.T
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [22]:
d = c.ravel()
print(d)

[1 4 2 5 3 6]


In [26]:
"""reshaping"""
e = a.ravel()
print(e)
print()

b = e.reshape((2,3))
print(b)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]


In [30]:
b[0, 1] = 400 #change value (row, column)
print(b)

[[  1 400   3]
 [  4   5   6]]


In [38]:
a = np.zeros((3, 2))
print(a)
print()

b = a.T.reshape(3*2)
print(b)
print()

b.reshape(3*2)
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0.]


In [39]:
b[0] = 70
print(b)

[70.  0.  0.  0.  0.  0.]


In [ ]:
"""1:01:00 / 1:06:54"""