In [20]:
import numpy as np

In [21]:
a = np.array([0,1,2,3]) #1D array
print(a)
print(a.ndim) #to get dimensions
print(a.shape) #to get rows and columns
print(len(a)) #to get length of array

[0 1 2 3]
1
(4,)
4


In [22]:
b = np.array([[0,1,2], [3,4,5]]) #2D array
print(b)
print(b.ndim)
print(b.shape)
print(len(b)) #returns the size of the first dimention

[[0 1 2]
 [3 4 5]]
2
(2, 3)
2


In [23]:
c = np.array([[[0,1], [2,3]], [[4, 5], [6,7]]]) #3D array
print(c)
print(c.ndim)
print(c.shape)
print(len(c))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
(2, 2, 2)
2
