In [ ]:
"""30:00 / 1:06:54"""

In [2]:
import numpy as np

In [3]:
a = np.arange(10)
print(a)
print()

b = a[::2] #to store slicing indexes (not store values)
print(b)
print()

print(np.shares_memory(a, b)) #to check if sampe memory are used at both palaces

[0 1 2 3 4 5 6 7 8 9]

[0 2 4 6 8]

True


In [4]:
a[0] = 10 #reflect a and b values
print(a)
print(b)
print()

b[0] = 20 #reflect a and b values
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]

[20  1  2  3  4  5  6  7  8  9]
[20  2  4  6  8]


In [6]:
a = np.arange(10)
b = a.copy() #to copy values
print(a)
print(b)
print()

a[1] = 50
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]

[ 0 50  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
a = np.arange(10)
b = a[::2].copy()
print(a)
print(b)
print()

a[2] = 60
print(a)
print(b)
print()

print(np.shares_memory(a,b))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]

[ 0  1 60  3  4  5  6  7  8  9]
[0 2 4 6 8]

False
