In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
"""elementwise operations"""
"""basic operations"""
b = a + 1
print(b)

[2 3 4 5]


In [11]:
c = a ** 2
print(c, c.dtype)

[ 1  4  9 16] int32


In [18]:
"""all arithmetic operates elementwise"""
a = np.array([2, 3, 4, 5])
b = np.ones(4) + 1
print(b)

c = a - b
print(c)

d = a * b
print(d)

[2. 2. 2. 2.]
[0. 1. 2. 3.]
[ 4.  6.  8. 10.]
