In [1]:
%pip install torch numpy --quiet

Note: you may need to restart the kernel to use updated packages.


In [3]:
import torch as tr #import pytorch

In [8]:
t = tr.tensor(4) #to create integer tensor
t

tensor(4)

In [10]:
t2 = tr.tensor(4.) #to create foat tensor
t2

tensor(4.)

In [11]:
t.dtype, t2.dtype

(torch.int64, torch.float32)

In [12]:
t.shape

torch.Size([])

In [13]:
"""creating a vector"""
v = tr.tensor([1., 2, 3, 4]) #it will convert all the numbers into float automatically
v

tensor([1., 2., 3., 4.])

In [14]:
v.dtype

torch.float32

In [15]:
v.shape

torch.Size([4])

In [16]:
"""creating a matrix (2D)"""
m = tr.tensor([[5., 6], [7,8], [9, 10]])
m

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [18]:
m.shape

torch.Size([3, 2])

In [19]:
m2 = tr.tensor([[[1,2,3], [3,4,5]], [[5,6,7], [7,8,9]]])
m2

tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]])

In [20]:
m2.shape

torch.Size([2, 2, 3])

In [25]:
"""compute derivatives"""
x = tr.tensor(3.)
w = tr.tensor(4., requires_grad=True)
b = tr.tensor(5., requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [26]:
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [27]:
y.backward() #to backpropagation

In [28]:
print(f"dy/dx: {x.grad}")
print(f"dy/dw: {w.grad}")
print(f"dy/db: {b.grad}")

dy/dx: None
dy/dw: 3.0
dy/db: 1.0
