In [1]:
import json

In [2]:
with open('dataset.json','r') as rf:
    intents = json.load(rf)

In [3]:
intents

{'intents': [{'tag': 'greeting',
   'patterns': ['hello', 'hi', 'hey', 'wake up', 'jarvis'],
   'responses': ['hello sir',
    'how are you sir',
    'always for you sir',
    'hello',
    "Here's your assistant"]},
  {'tag': 'bye',
   'patterns': ['bye', 'see you later', 'goodbye', 'bye bye', 'goodluck'],
   'responses': ['bye sir',
    'good bye sir',
    "it'll be nice to see you again",
    'see you later',
    'goodluck sir']},
  {'tag': 'health',
   'patterns': ['how are you', 'how are you feeling now', 'are you fine?'],
   'responses': ['fine sir', 'perfect', 'cool']}]}

In [4]:
all_words = []
tags = []
xy = []

In [5]:
from tp import tokenize, stem

In [6]:
for intent in intents['intents']:
    tag = intent['tag']
    tags.append(tag)
    for pattern in intent['patterns']:
        w = tokenize(pattern)
        all_words.extend(w)
        xy.append((w,tag))

In [7]:
print(all_words)
print(len(all_words))

['hello', 'hi', 'hey', 'wake', 'up', 'jarvis', 'bye', 'see', 'you', 'later', 'goodbye', 'bye', 'bye', 'goodluck', 'how', 'are', 'you', 'how', 'are', 'you', 'feeling', 'now', 'are', 'you', 'fine', '?']
26


In [8]:
ignore_words = ['?','!',',','.']
all_words = [stem(w) for w in all_words if w not in ignore_words]

In [9]:
print(all_words)
print(len(all_words))

['hello', 'hi', 'hey', 'wake', 'up', 'jarvi', 'bye', 'see', 'you', 'later', 'goodby', 'bye', 'bye', 'goodluck', 'how', 'are', 'you', 'how', 'are', 'you', 'feel', 'now', 'are', 'you', 'fine']
25


In [10]:
all_words = sorted(set(all_words))

In [11]:
print(all_words)
print(len(all_words))

['are', 'bye', 'feel', 'fine', 'goodby', 'goodluck', 'hello', 'hey', 'hi', 'how', 'jarvi', 'later', 'now', 'see', 'up', 'wake', 'you']
17


In [12]:
tags

['greeting', 'bye', 'health']

In [13]:
tags = sorted(set(tags))
tags

['bye', 'greeting', 'health']

In [14]:
xy

[(['hello'], 'greeting'),
 (['hi'], 'greeting'),
 (['hey'], 'greeting'),
 (['wake', 'up'], 'greeting'),
 (['jarvis'], 'greeting'),
 (['bye'], 'bye'),
 (['see', 'you', 'later'], 'bye'),
 (['goodbye'], 'bye'),
 (['bye', 'bye'], 'bye'),
 (['goodluck'], 'bye'),
 (['how', 'are', 'you'], 'health'),
 (['how', 'are', 'you', 'feeling', 'now'], 'health'),
 (['are', 'you', 'fine', '?'], 'health')]

In [15]:
x_train = []
y_train = []

In [16]:
from bow import BoW

In [17]:
for x,y in xy:
    bag = BoW(x,all_words)
    x_train.append(bag)

    label = tags.index(tag)
    y_train.append(label)

In [18]:
print(x_train)

[array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32), array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32), array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
      dtype=float32), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
      dtype=float32), array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.],
      dtype=float32), array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32), array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32), array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32), array([1., 0., 0., 

In [19]:
y_train

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

In [20]:
len(x_train)

13

In [21]:
import numpy as np

In [22]:
x_train = np.array(x_train)
y_train = np.array(y_train)

In [23]:
print(x_train)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [24]:
print(y_train)

[2 2 2 2 2 2 2 2 2 2 2 2 2]


In [25]:
from torch.utils.data import Dataset, DataLoader

In [26]:
batch_size = 8
hidden_size = 8
learning_rate = 0.001
input_size = len(x_train[0])
num_epochs = 1000
output_size = len(tags)

In [27]:
print(input_size)
print(hidden_size)
print(output_size)

17
8
3


In [28]:
class ChatDataset(Dataset):
    def __init__(self):
        self.n_samples = len(x_train)
        self.x_data = x_train
        self.y_data = y_train
    def __getitem__(self,index):
        return self.x_data[index],self.y_data[index]
    def __len__(self):
        return self.n_samples

In [29]:
dataset = ChatDataset()
train_loader = DataLoader(dataset=dataset,
                          batch_size=batch_size,
                          shuffle=True,
                          num_workers=0)

In [30]:
import torch

In [31]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [32]:
from neuron import NeuralNet
import torch.nn as nn

In [33]:
model = NeuralNet(input_size,hidden_size,output_size).to(device=device)

In [34]:
model

NeuralNet(
  (l1): Linear(in_features=17, out_features=8, bias=True)
  (l2): Linear(in_features=8, out_features=8, bias=True)
  (l3): Linear(in_features=8, out_features=3, bias=True)
  (relu): ReLU()
)

In [35]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters())

In [36]:
for epoch in range(num_epochs):
    for words,labels in train_loader:
        words = words.to(device)
        labels = labels.to(dtype=torch.long).to(device)

        output = model(words)
        loss = criterion(output,labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    if (epoch+1) % 100 == 0:
        print(f'epoch [{epoch+1}]/{num_epochs}, loss={loss.item():.4f}')
    print(f'final loss={loss.item():.4f}')

final loss=1.5310
final loss=1.5197
final loss=1.5180
final loss=1.5002
final loss=1.4960
final loss=1.4902
final loss=1.4784
final loss=1.4720
final loss=1.4596
final loss=1.4522
final loss=1.4461
final loss=1.4367
final loss=1.4297
final loss=1.4213
final loss=1.4152
final loss=1.4038
final loss=1.4006
final loss=1.3895
final loss=1.3850
final loss=1.3763
final loss=1.3642
final loss=1.3543
final loss=1.3536
final loss=1.3495
final loss=1.3381
final loss=1.3330
final loss=1.3267
final loss=1.3143
final loss=1.3133
final loss=1.2989
final loss=1.2918
final loss=1.2835
final loss=1.2798
final loss=1.2757
final loss=1.2659
final loss=1.2578
final loss=1.2524
final loss=1.2445
final loss=1.2443
final loss=1.2396
final loss=1.2358
final loss=1.2197
final loss=1.2238
final loss=1.2065
final loss=1.2078
final loss=1.1968
final loss=1.1896
final loss=1.1812
final loss=1.1862
final loss=1.1655
final loss=1.1587
final loss=1.1616
final loss=1.1610
final loss=1.1467
final loss=1.1388
final loss

In [37]:
data = {
    "model_state": model.state_dict(),
    "input_size": input_size,
    "hidden_size": hidden_size,
    "output_size": output_size,
    "all_words": all_words,
    "tags": tags}

In [38]:
file = "TrainData.pth"
torch.save(data,file)
print(f"Training completed! File has been saved to {file}")

Training completed! File has been saved to TrainData.pth


In [39]:
data = torch.load(file)

In [40]:
input_size = data["input_size"]
hidden_size = data["hidden_size"]
output_size = data["output_size"]
all_words = data["all_words"]
tags = data["tags"]
model_state = data["model_state"]

In [41]:
model = NeuralNet(input_size,hidden_size,output_size).to(device)
model.load_state_dict(model_state)
model.eval()

NeuralNet(
  (l1): Linear(in_features=17, out_features=8, bias=True)
  (l2): Linear(in_features=8, out_features=8, bias=True)
  (l3): Linear(in_features=8, out_features=3, bias=True)
  (relu): ReLU()
)

In [102]:
sentence = "are you"

In [104]:
sentence = tokenize(sentence)
X = BoW(sentence,all_words)
X = np.array(X)
X = X.reshape(1,X.shape[0])
X = torch.from_numpy(X).to(device)

In [106]:
output = model(X)

In [108]:
_,predicted = torch.max(output,dim=1)

In [110]:
tag = tags[predicted.item()]

In [112]:
probs = torch.softmax(output,dim=1)

In [114]:
prob = probs[0][predicted.item()]
prob.item()

0.9998018145561218

In [116]:
import random

In [118]:
if prob.item() > 0.75:
    for intent in intents['intents']:
        if tag == intent['tag']:
            reply = random.choice(intent['responses'])
    print(reply)

perfect
