<img src="neurons.jpg" width=400>

In [1]:
import numpy as np

In [5]:
x = np.array([[1,0,1,0],
              [1,0,1,1],
              [0,1,0,1]])
             
y = np.array([[1],[1],[0]])

<h2>Sigmoid Activation Function</h2>

In [35]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [37]:
print(x.shape)
print(x.shape[1])

(3, 4)
4


In [39]:
"""input layer neurons will be always equals to the number of columns"""
inputNeurons = x.shape[1]

"""hidden neurons we can decide by hit and trail"""
hiddenNeurons = 3

"""output neuron depends on number of classes we have in target columns"""
outputNeurons = 1

<p>
    weightsHidden = [4,3] <br>
    biasHidden = [1,3] <br>
    weightsOutput = [3,1] <br>
    biasOutput = [1,1]
</p>

In [42]:
weightsHidden = np.random.uniform(size=(inputNeurons,hiddenNeurons))
biasHidden = np.random.uniform(size=(1,hiddenNeurons))
weightsOutput = np.random.uniform(size=(hiddenNeurons,outputNeurons))
biasOutput = np.random.uniform(size=(1,outputNeurons))

<h2>Feedforward</h2>

<h3>Step-1 => apply dot product and add bias: f(x) = x.wh+bh</h3>

In [46]:
fx = np.dot(x,weightsHidden)+biasHidden
fx

array([[1.68822741, 0.70376596, 2.1309863 ],
       [2.29374465, 1.04882104, 2.77014614],
       [1.61562445, 0.61209995, 2.23323538]])

<h3>step-2 => apply activation function</h3>

In [49]:
hiddenLayer = sigmoid(fx)
hiddenLayer

array([[0.8439909 , 0.66902221, 0.8938786 ],
       [0.90835765, 0.74054844, 0.9410411 ],
       [0.8341908 , 0.64841968, 0.90319461]])

<h3>step-3 => apply dot product and add bias: f(x) = hiddenLayer.wo+bo</h3>

In [52]:
fx_ = np.dot(hiddenLayer,weightsOutput)+biasOutput
fx_

array([[1.24851859],
       [1.30405088],
       [1.2425433 ]])

<h3>step-4 => apply activation function</h3>

In [55]:
outputLayer = sigmoid(fx_)
outputLayer

array([[0.77704332],
       [0.78651595],
       [0.7760064 ]])