In [1]:
import numpy as np

In [3]:
"""creating 1D array"""
arr = np.array([1,2,3,4,5]) #create an array using list
arr

array([1, 2, 3, 4, 5])

In [6]:
arr2 = np.array((1,2,3,4,5)) #create an array using tuple
arr2

array([1, 2, 3, 4, 5])

In [10]:
"""creating 2D array"""
arr3 = np.array([[1,2,3], [1,2,3]]) #both length should be same
arr3

array([[1, 2, 3],
       [1, 2, 3]])

In [13]:
arr4 = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]], [[1,2,3],[4,5,6]]])
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [17]:
empty = np.empty([2,4]) #2 rows, 4 colums
empty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        8.90096090e-307],
       [1.89146896e-307, 7.56571288e-307, 3.11525958e-307,
        1.24610723e-306]])

In [19]:
np.empty([2,4])

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        8.90096090e-307],
       [1.89146896e-307, 7.56571288e-307, 3.11525958e-307,
        1.24610723e-306]])

In [21]:
np.zeros([2,5]) #2 rows and 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.zeros([2,5], dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
np.zeros([2,4], dtype=np.int8) #to put numpy's datatype

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [26]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.arange(0,6) #start, end (end will be excluded)

array([0, 1, 2, 3, 4, 5])

In [32]:
np.arange(0,10,2) #start, end, step

array([0, 2, 4, 6, 8])

In [37]:
np.linspace(0, 10, 5) #start, end, space (to create an array with linearspace)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [39]:
np.logspace(0,10,5)

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

In [41]:
np.full((3,4), 13) #row, columns, filling number

array([[13, 13, 13, 13],
       [13, 13, 13, 13],
       [13, 13, 13, 13]])

In [42]:
np.random.random([2,5])

array([[0.51411595, 0.52921157, 0.50101781, 0.96879815, 0.89889984],
       [0.28784067, 0.86070232, 0.6942838 , 0.18952709, 0.60107072]])