In [ ]:
"""15:06 / 24:14"""

In [45]:
import numpy as np

In [46]:
arr = np.array([[1,5,6,8,9], [7,8,9,5,4,]]) #2D array
arr

array([[1, 5, 6, 8, 9],
       [7, 8, 9, 5, 4]])

In [47]:
arr2 = np.array([[[1,5,6,8,9], [7,8,9,5,4]], [[9,4,6,8,2], [2,5,7,5,2]]]) #3D array

In [48]:
arr2.shape #to know shape

(2, 2, 5)

In [49]:
arr2.ndim #to know dimension

3

In [50]:
arr2.dtype #to know datatype

dtype('int32')

In [51]:
arr3 = np.array([1,5,6,8,9], dtype=np.int16) #to set datatype

In [52]:
arr3.dtype

dtype('int16')

In [53]:
arr2 = np.array([[[1,5,6,8,9], [7,8,9,5,4]], [[9,4,6,8,2], [2,5,7,5,2]]]) #3D array

In [54]:
arr2.size #to check number of total elements

20

In [55]:
arr2.ravel() #to change into 1D

array([1, 5, 6, 8, 9, 7, 8, 9, 5, 4, 9, 4, 6, 8, 2, 2, 5, 7, 5, 2])

In [56]:
arr2.reshape(2,10) #to change into 2D

array([[1, 5, 6, 8, 9, 7, 8, 9, 5, 4],
       [9, 4, 6, 8, 2, 2, 5, 7, 5, 2]])

In [61]:
np.sqrt(arr2) #to square root

array([[[1.        , 2.23606798, 2.44948974, 2.82842712, 3.        ],
        [2.64575131, 2.82842712, 3.        , 2.23606798, 2.        ]],

       [[3.        , 2.        , 2.44948974, 2.82842712, 1.41421356],
        [1.41421356, 2.23606798, 2.64575131, 2.23606798, 1.41421356]]])

In [62]:
arr4 = np.array([[0,1,5,0,6,9], [4,5,0,0,7,0]])

In [64]:
arr4

array([[0, 1, 5, 0, 6, 9],
       [4, 5, 0, 0, 7, 0]])

In [63]:
np.where(arr4>4) #check greater

(array([0, 0, 0, 1, 1], dtype=int64), array([2, 4, 5, 1, 4], dtype=int64))

In [66]:
np.count_nonzero(arr4) #to count nonzero element

7

In [67]:
np.nonzero(arr4)

(array([0, 0, 0, 0, 1, 1, 1], dtype=int64),
 array([1, 2, 4, 5, 0, 1, 4], dtype=int64))

In [69]:
arr4.nbytes #to check how many bytes occupied

48