In [ ]:
import numpy as np

In [2]:
"""example with list"""
py_lst_1 = [1,2,3]
py_lst_2 = [4,5,6]

In [3]:
py_lst_1+py_lst_2 #concatinate both list items

[1, 2, 3, 4, 5, 6]

In [4]:
"""example_with_numpy"""
a = np.array([1,2,3])
b = np.array([4,5,6])

In [12]:
a+b #sum both array items

array([5, 7, 9])

In [6]:
a+1 #sum one into 'a' array variable

array([2, 3, 4])

In [13]:
a-2 #minus two into 'a' array variable

array([-1,  0,  1])

In [14]:
a*5 #multiply a into 5

array([ 5, 10, 15])

In [18]:
arr = np.array([1, 2, 3])

In [19]:
arr[0]

1

In [21]:
arr[1]

2

In [22]:
arr[0]+arr[2]

4

In [23]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
"""example1"""
arr2[0][1]

2

In [25]:
"""example2"""
arr2[0,1]

2

In [27]:
arr2[0,1]+arr2[1,2] #add indivisual items

8