In [ ]:
"""
1D array:
    axis=0 #left to right

2D array:
    axis=0 #up to down
    axis=1 #left to right

3D array:
    axis=0 #front to back
    axis=1 #up to down
    axis=2 #left to right
"""

In [1]:
import numpy as np

In [4]:
"""1D array, axis=0 (left to right)"""
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [8]:
arr.sum() #left to right

6

In [9]:
arr.sum(axis=0) #left to right

6

In [16]:
"""2D array, axis=0 (up to down), axis=1 (left to right)"""
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr2.sum() #sum all the elements of array from "left to right" by default

45

In [18]:
arr2.sum(axis=0) #sum from "up to down"

array([12, 15, 18])

In [19]:
arr2.sum(axis=1) #sum from "left to right"

array([ 6, 15, 24])

In [20]:
"""3D array, axis=0(front to back), axis=1(up to down), axis=2(left to right)"""
arr3 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[11,22,33], [44, 55, 66], [77, 88, 99]]])
arr3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99]]])

In [21]:
arr3.sum(axis=0)

array([[ 12,  24,  36],
       [ 48,  60,  72],
       [ 84,  96, 108]])

In [23]:
arr3.sum(axis=1)

array([[ 12,  15,  18],
       [132, 165, 198]])

In [24]:
arr3.sum(axis=2)

array([[  6,  15,  24],
       [ 66, 165, 264]])

In [34]:
arr4 = np.array([[7,2,10], [4,5,6]])
arr4

array([[ 7,  2, 10],
       [ 4,  5,  6]])

In [41]:
arr4.argmin(axis=0) #not clear

array([1, 0, 1], dtype=int64)

In [39]:
arr4.argmax(axis=0)

array([0, 1, 0], dtype=int64)