In [1]:
import numpy as np

In [2]:
"""Define matrix"""
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [4]:
"""Function to calculate minors"""
def get_minors(mat,i,j):
    return np.delete(np.delete(mat,i,axis=0), j,axis=1)

In [5]:
"""Calculate minors for each element in the matrix"""
minors = np.zeros_like(matrix, dtype=float)
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        minors[i,j] = np.linalg.det(get_minors(matrix, i, j))

print(f"Original Matrix:\n{matrix}")
print(f"Minors Matrix:\n{minors}")

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Minors Matrix:
[[ -3.  -6.  -3.]
 [ -6. -12.  -6.]
 [ -3.  -6.  -3.]]
