In [1]:
import numpy as np

In [9]:
"""Create a sample 2x2 matrix"""
matrix = np.array([[1,2], [8,7]])

"""Find the determinant"""
determinant = np.linalg.det(matrix)
print(f"Matrix: {matrix}")
print(f"Determinant of the matrix: {determinant}")

Matrix: [[1 2]
 [8 7]]
Determinant of the matrix: -8.999999999999998


In [10]:
"""Create a sample 3x3 matrix"""
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

"""Find the determinant"""
determinant = np.linalg.det(matrix)
print(f"Matrix: {matrix}")
print(f"Determinant of the matrix: {determinant}")

Matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of the matrix: 0.0


In [11]:
"""Create a sample 3x3 matrix"""
matrix = np.array([[1,-1,1], [2,1,1], [-1,-2,2]])

"""Find the determinant"""
determinant = np.linalg.det(matrix)
print(f"Matrix: {matrix}")
print(f"Determinant of the matrix: {determinant}")

Matrix: [[ 1 -1  1]
 [ 2  1  1]
 [-1 -2  2]]
Determinant of the matrix: 6.0
