In [1]:
import numpy as np

In [2]:
myArr = np.array([2,3,5,7,1]) #create array using list
myArr

array([2, 3, 5, 7, 1])

In [3]:
myArr2 = np.array((1,2,3,4,5)) #create array using tuple
myArr2

array([1, 2, 3, 4, 5])

In [6]:
"""creating 2D array"""
myArr3 = np.array([[1,2,3], [4,5,6]]) #both length should be same
myArr3

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
"""creating 3D array"""
myArr4 =np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
myArr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [14]:
myArr4.ndim

3

In [12]:
myArr4.shape

(3, 2, 3)

In [15]:
len(myArr4)

3