In [1]:
import numpy as np

In [6]:
"""example with list"""
lst1 = [1,2,3]
lst2 = [4,5,6]

In [7]:
lst1+lst2 #it will concatinate both list items

[1, 2, 3, 4, 5, 6]

In [11]:
"""example with nupy"""
a = np.array([1,2,3])
b = np.array([4,5,6])

In [12]:
a+b #it will sum both np items

array([5, 7, 9])

In [13]:
a+1 #to sum one into all "a" items

array([2, 3, 4])

In [14]:
a-1 #to minus one into all "a" items

array([0, 1, 2])

In [16]:
a*5 #to multiply by 5 with all "a" items

array([ 5, 10, 15])

In [18]:
b[0]+b[2] #to sum of b variable zero's and 2nd index items

10