In [1]:
import numpy as np

In [6]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a[1:8] #index 1 to 8 (8th index will be excluded)

array([2, 3, 4, 5, 6, 7, 8])

In [10]:
a[1:8:2] #startIndex, endIndex, step

array([2, 4, 6, 8])

In [11]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a[5:] = 8 #put 8 after fifth index
a

array([1, 2, 3, 4, 5, 8, 8, 8, 8])

In [20]:
a = np.arange(1,10+1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
a[::-1] #reverse numbers

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])