In [25]:
import numpy as np

<h1>Create a reflected copy<h1>

In [26]:
a = np.arange(1,10+1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
b = a #to store slicing indexs (not store value)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.shares_memory(a, b) #to check if both data are stored at same memory location

True

In [29]:
a[4] = 10 #reflect a and b values
print(a)
print(b)

[ 1  2  3  4 10  6  7  8  9 10]
[ 1  2  3  4 10  6  7  8  9 10]


<h1>Create an other copy</h1>

In [30]:
a = np.arange(1,10+1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
b = a.copy() #to create a other copy
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a[1] = 8
print(a)
print(b)

[ 1  8  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


<h1>Create a reflected copy by slicing</h1>

In [33]:
a = np.arange(1,10+1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
b = a[:5]
b

array([1, 2, 3, 4, 5])

In [35]:
a[2] = 8 #change value
print(a)
print(b)

[ 1  2  8  4  5  6  7  8  9 10]
[1 2 8 4 5]


In [36]:
np.shares_memory(a,b)

True

<h1>Create an other copy by slicing</h1>

In [37]:
a = np.arange(1,10+1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
b = a[:5].copy()
b

array([1, 2, 3, 4, 5])

In [39]:
a[3] = 8
print(a)
print(b)

[ 1  2  3  8  5  6  7  8  9 10]
[1 2 3 4 5]


In [40]:
np.shares_memory(a,b)

False