In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5], [2,3,4,5,6]])
a

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [4]:
np.sum(a) #to sum all values

35

In [5]:
np.sum(a, axis=0) #sum values by column

array([ 3,  5,  7,  9, 11])

In [16]:
np.sum(a, axis=1) #sum values by row

array([15, 20])

In [19]:
np.min(a) #to check minimum value of all elements

1

In [21]:
a.min(axis=1) #by column

array([1, 2])

In [23]:
np.max(a) #to check maximum value of all elements

6

In [25]:
np.max(a, axis=1) #by column

array([5, 6])

In [27]:
np.argmin(a) #to get minimum value's index of all elements

0

In [28]:
np.argmin(a, axis=1)

array([0, 0], dtype=int64)

In [29]:
a.argmax() #to get maximum values index

7

In [29]:
np.argmax(a, axis=1)

array([4, 4], dtype=int64)

In [38]:
a = np.array([1,2,3,5,7,2,7,5,9])
a

array([1, 2, 3, 5, 7, 2, 7, 5, 9])

In [39]:
a.mean() #to get mean of "a"

4.555555555555555

In [45]:
np.median(a)

5.0