In [42]:
"""18:42 / 56:17"""
import numpy as np

In [43]:
myarry = np.array([3,6,32,7]) #create array
myarry

array([ 3,  6, 32,  7])

In [44]:
myarry.dtype #to check datatype / bit

dtype('int32')

In [45]:
new_arry = np.array([3,6,32,7], np.int64) #set bit
new_arry

array([ 3,  6, 32,  7], dtype=int64)

In [46]:
new_arry.dtype

dtype('int64')

In [47]:
myarry[1] = 42 #to change value
myarry

array([ 3, 42, 32,  7])

In [48]:
myarry.shape #to check dimension

(4,)

In [49]:
myarry2 = np.array([[2, 4, 7, 11]]) #create 2D array
myarry2

array([[ 2,  4,  7, 11]])

In [50]:
myarry2.shape

(1, 4)