In [1]:
"""19:00 / 56:17"""
import numpy as np

In [11]:
myArry = np.array([1,3,5,8]) #creating 1D array

In [12]:
myArry2 = np.array([[2,5,7,5]]) #creating 2D array

In [17]:
myArry.shape

(4,)

In [18]:
myArry2.shape

(1, 4)

In [13]:
myArry

array([1, 3, 5, 8])

In [14]:
myArry2

array([[2, 5, 7, 5]])

In [16]:
myArry[2] = 44 #changing the value
myArry

array([ 1,  3, 44,  8])

In [24]:
myArry2[0, 1] = 33
myArry2

array([[ 2, 33,  7,  5]])